### ISSUE TITLE
Cannot run train.py in part_seg

### ISSUE THREAD

**Issue by YiruS** [charlesq34/pointnet#10]
Hi,

I'm currently running the PointNet code. However, I cannot run train.py in part_seg as mentioned in the "README". Also there seems to be bugs in the code -- I myself fixed some. Is this code the final one? It seems like this is not the complete or even wrong version.

Thanks,
Yiru

**Comment by YiruS** [comment]
Found out that the problem came from loading training data. I used Titan X and the error would rise up if gpu cannot load data fully. Problem is fixed after allocating more memory.

**Comment by mescpla** [comment]
I also fixed it with a lower number of batches... is not the perfect result, but it works.
