### ISSUE TITLE
error occurs when run sh download_data.sh in sem_seg

### ISSUE THREAD

**Issue by joanne1112** [charlesq34/pointnet#127]
Hi all,
An error occurs when I run sh download_data.sh and it says the server does not respond. So I download the zip file from the website and unzip it. 
I have run `python collect_indoor3d_data.py` and get all the .npy files while when I run `python gen_indoor3d_h5.py` , an error occurs for some of the .npy files and it says:
`unsupported operand type(s) for +: 'range' and 'list'`
which is line 125 in `indoor3d_util.py` : ` return concatenate([data, dup_data], 0), range(N) + list(sample)`

does anyone run into the same situation?
Thank you for sharing!

**Comment by STARBOYsachin** [comment]
Did you find the answer?
