### ISSUE TITLE
Question about .obj files of sem_seg results.

### ISSUE THREAD

**Issue by yikakabu** [charlesq34/pointnet#134]
Hello. When I run batch_inference.py. There are some OBJ files created for prediciton visualization in log6/dump as README told. But I don't know how to open a obj flie to visualization.I have tried to use ctmviewer to view the obj flies, but failed. It can't be displayed.
Thanks.

**Comment by Lsesasfs** [comment]
You can open .obj files via some free 3D mesh processing software like MeshLab or CloudCompare.

**Comment by yikakabu** [comment]
@Lsesasfs  That's work. THANKS a lot.

**Comment by ming-hong** [comment]
I was opening .obj files in CloudCompare but it doesn't visualize the color. Is anyone encountering the same issue or succeeded in visualizing with colors? 
Thank you!

**Comment by aiserg** [comment]
@ming-hong Hey! Did you resolve the problem with colors visualization?

**Comment by JiahaoXia** [comment]
I am also confused with coloring the point cloud (.obj file) based on the segmented result (.txt).
