### ISSUE TITLE
Unable to establish SSL connection when running train.py

### ISSUE THREAD

**Issue by andrewsunst** [charlesq34/pointnet#139]
Hi,
The link https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip isn't available now. Is there any other data to start with?

Thank you.

**Comment by xiashaobo** [comment]
> Hi,
> The link https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip isn't available now. Is there any other data to start with?
> 
> Thank you.
The SAME problem. Waiting... ...
