### ISSUE TITLE
how to download data?

### ISSUE THREAD

**Issue by shangyouai** [charlesq34/pointnet#14]
instruction said that: Point clouds of ModelNet40 models in HDF5 files will be automatically downloaded (416MB) to the data folder,but it didn't happened to me.
I download the ModelNet40 data from the link but it was in .off format. I'm sorry because i'm new to python and tensorflow.
environments are: windows 7,python 3.5.3 , tensorflow1.1.0

**Comment by charlesq34** [comment]
Hi @shangyouai 

I think it was because you used Windows. The script assumes a Linux system..
You can checkout provider.py there is a download link :)

Best,
Charles
