### ISSUE TITLE
How to create my own dataset for part_seg?

### ISSUE THREAD

**Issue by percyfan** [charlesq34/pointnet#148]
First, thanks for the great code! 
Now I'm having trouble with creating custom data set for part segmentation.
I have some volume data and I converted them to mesh as .ply file, and then I converted the .ply files to point cloud data with a software called CloudCompare.
But the point cloud data set is as .pts file and every part of the object is as .seg file which are not supported by CloudCompare.

Can anyone give me some suggestions on how to create .pts and .seg file?
Any suggestion will be appreciated.

**Comment by Leerw** [comment]
have you got the solution? @percyfan

**Comment by arunumd** [comment]
Even I am interested in an answer to this question. How do we create **.seg** files ?

**Comment by HwanWoongLee** [comment]
help :(
