### ISSUE TITLE
No nonlinearities?

### ISSUE THREAD

**Issue by EndingCredits** [charlesq34/pointnet#16]
I can't see any non-linearities/activation functions in your model. Is this intentional?

I suspect this is why you need such a big embedding layer. In my own experiments I found that you can make this layer pretty small (even as low as 8 in some cases!), especially if you use set-wide information in the transformations.

**Comment by JulesGM** [comment]
They're included in the layer definitions at https://github.com/charlesq34/pointnet/blob/master/utils/tf_util.py

**Comment by EndingCredits** [comment]
Ah, I knew I must have made a mistake somewhere. I had googled tf_utils, for some reason I thought it was a standard tf library (it's included in the source, but replicated here) which has the identity as the standard activation function.

Still, I'm surprised such big layer sizes are required. [https://arxiv.org/abs/1611.04500](https://arxiv.org/abs/1611.04500) reports similar results with layer sizes of 256 (although they go up to 512 for 5000 points, and obviously it's a different architecture). Is it just a case of a few percent different?

**Comment by charlesq34** [comment]
@EndingCredits you are welcomed to try different layer configurations. Let us know if you get good results with fewer neurons!:)
