### ISSUE TITLE
how to visualize the segmentation results

### ISSUE THREAD

**Issue by HanochZzhou** [charlesq34/pointnet#167]
thanks for sharing this work. I am new to semantic segmentation, can you tell me how to visualize the results and the raw point clouds? 
Thank you very much!

**Comment by shubhamwagh** [comment]
Segmentation results are dumped in log6/dump/ folder which contains ground truth and predicted ".obj" files. You can open .obj files via some free 3D mesh processing software like MeshLab etc.

**Comment by HanochZzhou** [comment]
sorry, I didn't say it clearly. I mean, how to visualize the source point clouds. I am new to point clouds. Thanks for your help!

**Comment by shubhamwagh** [comment]
* First download the dataset from the link mentioned in ReadeMe file.
* Run `python collect_indoor3d_data.py`  from sem_seg folder
* It will create new folder **stanford/_indoor3d** and will dumpy all source pointclouds in .npy file format.
* To visualize them run the following script (open3d needs to be installed to visualize them)
``` python
from open3d import *
import numpy as np

#give path to ".npy" file
pc = np.load('/home/qbot/pointnet/data/stanford_indoor3d/Area_1_conferenceRoom_1.npy') 

pcd = PointCloud()
pcd.points = Vector3dVector(pc[:,0:3])
pcd.colors = Vector3dVector(pc[:,3:6]/ 255.0)  #open3d requires colors to be in range[0,1]
draw_geometries([pcd])
```
I hope this helps.

**Comment by HanochZzhou** [comment]
Oh, thanks,  that's great! Thank you very much!

**Comment by thirdlastletter** [comment]
> Segmentation results are dumped in log6/dump/ folder which contains ground truth and predicted ".obj" files. You can open .obj files via some free 3D mesh processing software like MeshLab etc.

Hi,
after running train.py with my own data there is no dump folder. Have you encountered this problem before? Thank you

**Comment by shubhamwagh** [comment]
Hi @thirdlastletter ,
dump folder is created during batch inference. 
If you properly see the ReadMe file for sem_seg 
1) For training it requires user to give log directory input .
`python train.py --log_dir log6 --test_area 6`

2) It is during testing or inferencing time dump folder is created as it requires user to give dump directory
`python batch_inference.py --model_path log6/model.ckpt --dump_dir log6/dump --output_filelist log6/output_filelist.txt --room_data_filelist meta/area6_data_label.txt --visu`

**Comment by thirdlastletter** [comment]
@shubhamwagh Hi thank you! One question, I have a 3fold cross validation set. I can use train.py with both my train and test data. What do I need batch_interference for then? Just for the visualization/prediction? So I need to use both train.py and batch_intereference.py on one set of train/test files, and repeat this for the other 2 versions? Thank you.

**Comment by shubhamwagh** [comment]
Hi @thirdlastletter 
So considering you have 3-fold cross validation set (e.g. datatset_0, dataset_1, dataset_2). You will have to train your model 3 times i.e.
1) train using dataset_0, dataset_1 and validate on dataset_2
` python train.py --log_dir log2 --test_area dataset_2`
2) train using dataset_0, dataset_2 and validate on dataset_1
` python train.py --log_dir log1 --test_area dataset_1`
3) train using dataset_1, dataset_2 and validate on dataset_0
` python train.py --log_dir log0 --test_area dataset_0`

Once your model is fully trained, you can use a different test-set having the same distribution as the train and validation set for inferencing and getting predictions from your learned model. 

`python batch_inference.py --model_path log6/model.ckpt --dump_dir log6/dump --output_filelist log6/output_filelist.txt --room_data_filelist meta/area6_data_label.txt --visu`

Yes this is mainly to get immediate predictions of the learned model and and that script dumps segmented point cloud files in order to visualize.

If you don't have test-set , it is still fine you can randomly sample from your existing 3-fold cross validation set and test on those.

**Comment by thirdlastletter** [comment]
@shubhamwagh 
Thank you so much! I understand now :)

**Comment by HanochZzhou** [comment]
@shubhamwagh 
Oh, excuse me,  I am coming again. after I trained and evaluated the ModelNet40 dataset, the dump fold just contains _pred_label.txt_  file. could you tell me what to do if I want to visualize the segmentation result! Thanks a lot!

**Comment by shubhamwagh** [comment]
Hi @HanochZzhou 
It Looks you are checking the wrong folder. Segmentation results are dumped in the path /pointnet/sem_seg/log6/dump folder and not the pointnet/dump folder

**Comment by HanochZzhou** [comment]
Hi, @shubhamwagh  Thanks for your reply.
In fact, I understand the whole process of semantic segmentation. But in classification and part-segmentation with ModelNet40 dataset and ShapeNet dataset, the test results just are __pred_lable.txt__ file in _dump_ fold. Do you have any idea to visualize the classification and part-segmentation results?

**Comment by shubhamwagh** [comment]
Hi @HanochZzhou 
Please open new issue for that. Just to keep individual thread topics separated for other people.
Thanks

**Comment by HanochZzhou** [comment]
OK, Thanks!

**Comment by kiranintellify** [comment]
Hi,@shubhamwagh 
How to test only one file i.e office in semantic segmentation. Is it necessary to give proceessed .npy file.
Can we test with office.txt file.

**Comment by renmaqilong** [comment]
> Segmentation results are dumped in log6/dump/ folder which contains ground truth and predicted ".obj" files. You can open .obj files via some free 3D mesh processing software like MeshLab etc.

When I open .obj files via MeshLab and Cloudcompare ,  the color information can't be observed.

**Comment by limt15** [comment]
Hi @shubhamwagh 
I have some trouble in visualizing the part segmentation results.
Could you please help me to solve this problem?
Many thanks!

**Comment by limt15** [comment]
> * First download the dataset from the link mentioned in ReadeMe file.
> * Run `python collect_indoor3d_data.py`  from sem_seg folder
> * It will create new folder **stanford_indoor3d** and will dumpy all source pointclouds in .npy file format.
> * To visualize them run the following script (open3d needs to be installed to visualize them)
> 
> ```python
> from open3d import *
> import numpy as np
> 
> #give path to ".npy" file
> pc = np.load('/home/qbot/pointnet/data/stanford_indoor3d/Area_1_conferenceRoom_1.npy') 
> 
> pcd = PointCloud()
> pcd.points = Vector3dVector(pc[:,0:3]) # XYZ points
> pcd.colors = Vector3dVector(pc[:,3:6]/ 255.0)  #open3d requires colors (RGB) to be in range[0,1]
> draw_geometries([pcd])
> ```
> 
> You should see something like this for **Area_1_conferenceRoom_1.npy** as below.
> ![Screenshot from 2019-05-08 10-16-13](https://user-images.githubusercontent.com/22571244/57364106-640c7e80-717a-11e9-9fe7-dd72be7cf8e5.png)
> 
> I hope this helps.

I used this script, but there is a error:
`NameError: name 'PointCloud' is not defined`

What is the `pcd = PointCloud()`?
Could you help me to solve this problem?

**Comment by shubhamwagh** [comment]
@limt15 , recently open3d updated their api version. Kindly find the updated script.

```
import open3d
import numpy as np

#give path to ".npy" file
pc = np.load('/home/qbot/pointnet/data/stanford_indoor3d/Area_1_conferenceRoom_1.npy') 

pcd = open3d.geometry.PointCloud()
pcd.points = open3d.utility.Vector3dVector(pc[:,0:3]) # XYZ points
pcd.colors = open3d.utility.Vector3dVector(pc[:,3:6]/ 255.0)  #open3d requires colors (RGB) to be in range[0,1]
open3d.visualization.draw_geometries([pcd])
```

**Comment by limt15** [comment]
> @limt15 , recently open3d updated their api version. Kindly find the updated script.
> 
> ```
> import open3d
> import numpy as np
> 
> #give path to ".npy" file
> pc = np.load('/home/qbot/pointnet/data/stanford_indoor3d/Area_1_conferenceRoom_1.npy') 
> 
> pcd = open3d.geometry.PointCloud()
> pcd.points = open3d.utility.Vector3dVector(pc[:,0:3]) # XYZ points
> pcd.colors = open3d.utility.Vector3dVector(pc[:,3:6]/ 255.0)  #open3d requires colors (RGB) to be in range[0,1]
> open3d.visualization.draw_geometries([pcd])
> ```

Thank you very much!
I have solved this problem, and I also have visualized the `.txt` file successfully.

By the way, I look forward to further discussion with you in the future～～～

**Comment by ZJU-PLP** [comment]
> > Segmentation results are dumped in log6/dump/ folder which contains ground truth and predicted ".obj" files. You can open .obj files via some free 3D mesh processing software like MeshLab etc.
> 
> When I open .obj files via MeshLab and Cloudcompare , the color information can't be observed.

Hi, did you slove the color problem when you visualize the obj result by using MeshLab?
Could you mind sharing the method? Thanks a lot!

**Comment by Yujun1212** [comment]
@limt15 Hi! I feel happy for you to see you have solved this question of visualization. I also have the same question. Could you share me the detail of this method? Thank you!

**Comment by noridayu1998** [comment]
> * First download the dataset from the link mentioned in ReadeMe file.
> * Run `python collect_indoor3d_data.py`  from sem_seg folder
> * It will create new folder **stanford_indoor3d** and will dumpy all source pointclouds in .npy file format.
> * To visualize them run the following script (open3d needs to be installed to visualize them)
> 
> ```python
> from open3d import *
> import numpy as np
> 
> #give path to ".npy" file
> pc = np.load('/home/qbot/pointnet/data/stanford_indoor3d/Area_1_conferenceRoom_1.npy') 
> 
> pcd = PointCloud()
> pcd.points = Vector3dVector(pc[:,0:3]) # XYZ points
> pcd.colors = Vector3dVector(pc[:,3:6]/ 255.0)  #open3d requires colors (RGB) to be in range[0,1]
> draw_geometries([pcd])
> ```
> 
> You should see something like this for **Area_1_conferenceRoom_1.npy** as below.
> ![Screenshot from 2019-05-08 10-16-13](https://user-images.githubusercontent.com/22571244/57364106-640c7e80-717a-11e9-9fe7-dd72be7cf8e5.png)
> 
> I hope this helps.

hi! may I know what data you use? it is shapenetpart?

**Comment by IfrahIdrees** [comment]
Hi @limt15 I am happy that you solved the visualization of segmentaion result. Can you please share details of how you visualize scene segmentation results?
