### ISSUE TITLE
Using conv2d rather than linear layer

### ISSUE THREAD

**Issue by Steve-Tod** [charlesq34/pointnet#169]
Hi, I read your paper and your code and I got one question. Why do you use conv2D instead of linear to implement mlp? Like here:
https://github.com/charlesq34/pointnet/blob/d64d2398e55b24f69e95ecb549ff7d4581ffc21e/models/pointnet_cls.py#L44

**Comment by luis-gonzales** [comment]
@Steve-Tod It's simply a convenient way to do the weight-sharing of a MLP (across number of samples)

**Comment by Steve-Tod** [comment]
I got it, Thanks.
