### ISSUE TITLE
Confusion with pointnet_cls.py

### ISSUE THREAD

**Issue by phoenixSP** [charlesq34/pointnet#17]
In pointnet_cls.py why have you expanded the dimension of the transformed input point cloud?

 `  def get_model(point_cloud, is_training, bn_decay=None):
    """ Classification PointNet, input is BxNx3, output Bx40 """
      batch_size = point_cloud.get_shape()[0].value
      num_point = point_cloud.get_shape()[1].value
      end_points = {}

    with tf.variable_scope('transform_net1') as sc:
        transform = input_transform_net(point_cloud, is_training, bn_decay, K=3)
    point_cloud_transformed = tf.matmul(point_cloud, transform)
    input_image = tf.expand_dims(point_cloud_transformed, -1)

    net = tf_util.conv2d(input_image, 64, [1,3],
                         padding='VALID', stride=[1,1],
                         bn=True, is_training=is_training,
                         scope='conv1', bn_decay=bn_decay)`

**Comment by EndingCredits** [comment]
It's because conv2d is used, so we need to add an extra 'dummy' dimension, as we only want to stride across one dimension.

An alternative could be to use conv1d but this does the same thing anyway (uses conv2d) and would mean tf would shape back and forth pointlessly in between convolutions.

**Comment by phoenixSP** [comment]
I was looking through the code of tf_util.conv2d, basically the input_image should be 4D tensor.

**Comment by charlesq34** [comment]
Hi phoenixSP,

it's just a choice of implementation. You can also use conv1d (input will be 3D) or just batch matrix multiplication (input will be 2D) with a few more transformations.
