### ISSUE TITLE
How to visualize critical point sets

### ISSUE THREAD

**Issue by Liu-Feng** [charlesq34/pointnet#175]
I meet some troubles about the critical sets, shown in Figure 7 in paper.
The feature used to visualize critical sets is global, local or concatenated future. As there are there models of network in your projects, and corresponding with three different feature, I cannot make scene that which feature is used to generate critical set.
Moreover, can anyone share the code that can be used to visualize critical sets.

**Comment by mblaettler** [comment]
Hi @Liu-Feng 
Did you find a solution on how to extract the critical set of points?  
I'm currently doing some experiments with regard to zero padding incomplete point clouds and it would be interesting to visualize and compare the critical point set of a zero and non zero padded point cloud.

**Comment by Liu-Feng** [comment]
> Hi @Liu-Feng
> Did you find a solution on how to extract the critical set of points?
> I'm currently doing some experiments with regard to zero padding incomplete point clouds and it would be interesting to visualize and compare the critical point set of a zero and non zero padded point cloud.



> Hi @Liu-Feng
> Did you find a solution on how to extract the critical set of points?
> I'm currently doing some experiments with regard to zero padding incomplete point clouds and it would be interesting to visualize and compare the critical point set of a zero and non zero padded point cloud.

Hi, I find the implementation of visualizing critical points in https://github.com/Wind-Wing/pointnet-visualization.
However, the time cost is higher in orinal code, I re-implementation it by numpy array, which is almost ten times faster.

**Comment by mblaettler** [comment]
Thank you very much. I'll take a look at it.
