### ISSUE TITLE
IOU computation

### ISSUE THREAD

**Issue by johnwlambert** [charlesq34/pointnet#18]
Hi Charles, I see that you use [the following line of code](https://github.com/charlesq34/pointnet/blob/master/sem_seg/eval_iou_accuracy.py#L35)

`iou = true_positive_classes[i]/float(gt_classes[i]+positive_classes[i]-true_positive_classes[i]) `

I'm a bit confused by the what the difference between these variables. [Others use this](https://arxiv.org/pdf/1704.03847.pdf) or [this definition](https://liu.diva-portal.org/smash/get/diva2:1091059/FULLTEXT01.pdf), both of which seem equivalent to each other, but not equivalent to your definition.

<img width="509" alt="screen shot 2017-06-29 at 12 24 07 am" src="https://user-images.githubusercontent.com/16724970/27671368-5e28102c-5c61-11e7-852e-0edf33bf01b1.png">
<img width="338" alt="screen shot 2017-06-29 at 12 21 43 am" src="https://user-images.githubusercontent.com/16724970/27671369-5e2bb6be-5c61-11e7-9e61-91bab1045fcb.png">

**Comment by charlesq34** [comment]
Hi John,

They are equivalent.

gt = TP + FN
positive = TP + FP

therefore gt+positive-TP = TP+FN+TP+FP-TP = TP+FN+FP

Best,
Charles

**Comment by piyushsingh2k7** [comment]
@johnwlambert : Hi john when I was implementing this sentence "To evaluate overall segmentation accuracy, we evaluate 6 models on their corresponding test areas and use `eval_iou_accuracy.py` to produce point classification accuracy and IoU as reported in the paper." Actually, the file name" all_pred_data_label_filelist.txt" is not there.  How can I get this "all_pred_data_label_filelist.txt"  and how I will proceed to evaluate the ground and predicted accuracy using IoU ....? Thanks in advance if you could help me.
