### ISSUE TITLE
Problems in predicting own data in sem seg

### ISSUE THREAD

**Issue by RollingIsland** [charlesq34/pointnet#182]
- ### I modified the script as follow to process my own data:
     1. I use text file as input, not npy file. But the data forms are same in .txt and .npy. 
     2. There is no label for my own data, so those relevant lines in the scripts were deleted. 

         I think these changes should not affect the function of the model, however the result was totally wrong.

- ### The form of data like:

```
-0.00650059 49.97880156 -125.81439983 254 254 254
-0.02650009 49.97840101 -125.81430065 251 251 251
-0.01760040 49.99639875 -125.81469738 246 246 246
0.00240005 49.99739820 -125.81400311 248 248 248
-0.01719986 49.96049864 -125.81439983 252 252 252
0.01370014 49.98089964 -125.81479656 255 255 255
0.00600018 49.96239836 -125.81449902 251 251 251
```
The previous 3 columns are **XYZ**, the rest are **RGB (not true color but grey value)**.

- ### The seg result is totally wrong:

```
0.559700 47.716499 -126.147400 139 139 139 1.000000 0
0.592000 47.458698 -127.404404 67 67 67 1.000000 0
0.013400 47.426899 -126.498901 148 148 148 1.000000 0
0.274700 47.592098 -125.803002 200 200 200 1.000000 0
0.966400 47.919499 -126.439301 157 157 157 1.000000 0
0.876899 47.995201 -128.726700 132 132 132 1.000000 0
0.422400 47.648601 -126.555298 85 85 85 1.000000 0
0.152500 47.502899 -126.407097 155 155 155 1.000000 0
```
All points were classified as class 0, and the probabilities given were 1. 
Can't figure out the reason.   

        There's the source code: 
     ### 1.  const in indoor3d_util.py
```python
g_classes = [x.rstrip() for x in open(os.path.join(BASE_DIR, 'meta/class_names.txt'))]
g_class2label = {cls: i for i,cls in enumerate(g_classes)}
g_class2color = {'ceiling': [0,255,0],
                 'floor':   [0,0,255],
                 'wall':    [0,255,255],
                 'beam':        [255,255,0],
                 'column':      [255,0,255],
                 'window':      [100,100,255],
                 'door':        [200,200,100],
                 'table':       [170,120,200],
                 'chair':       [255,0,0],
                 'sofa':        [200,100,100],
                 'bookcase':    [10,200,100],
                 'board':       [200,200,200],
                 'clutter':     [50,50,50]} 
g_easy_view_labels = [7,8,9,10,11,1]
g_label2color = {g_classes.index(cls): g_class2color[cls] for cls in g_classes}

import argparse
import os
import sys
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(BASE_DIR)
sys.path.append(BASE_DIR)
from model import *

parser = argparse.ArgumentParser()
parser.add_argument('--gpu', type=int, default=0, help='GPU to use [default: GPU 0]')
parser.add_argument('--batch_size', type=int, default=1, help='Batch Size during training [default: 1]')
parser.add_argument('--num_point', type=int, default=4096, help='Point number [default: 4096]')
parser.add_argument('--model_path', default='log/model.ckpt', help='model checkpoint file path')
parser.add_argument('--no_clutter', action='store_true', help='If true, donot count the clutter class')
FLAGS = parser.parse_args()

BATCH_SIZE = FLAGS.batch_size
NUM_POINT = FLAGS.num_point
MODEL_PATH = FLAGS.model_path
GPU_INDEX = FLAGS.gpu
DUMP_DIR = 'dump'
if not os.path.exists(DUMP_DIR):
    os.mkdir(DUMP_DIR)

NUM_CLASSES = 13

```

### 2.  part modified from [batch_inference.py](https://github.com/charlesq34/pointnet/blob/master/sem_seg/batch_inference.py)
```python
def predict():
    is_training = False
     
    with tf.device('/gpu:'+str(GPU_INDEX)):
        pointclouds_pl, labels_pl = placeholder_inputs(BATCH_SIZE, NUM_POINT)
        is_training_pl = tf.placeholder(tf.bool, shape=())

        # simple model
        pred = get_model(pointclouds_pl, is_training_pl)
        loss = get_loss(pred, labels_pl)
        pred_softmax = tf.nn.softmax(pred)
 
        # Add ops to save and restore all the variables.
        saver = tf.train.Saver()
        
    # Create a session
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    config.allow_soft_placement = True
    config.log_device_placement = True
    sess = tf.Session(config=config)

    # Restore variables from disk.
    saver.restore(sess, MODEL_PATH)
    print('  Model restored.')

    ops = {'pointclouds_pl': pointclouds_pl,
           'labels_pl': labels_pl,
           'is_training_pl': is_training_pl,
           'pred': pred,
           'pred_softmax': pred_softmax,
           'loss': loss}
    
    total_correct = 0
    total_seen = 0
    #room_path = input(' Input point cloud file path: ')
    room_path = 'E:/Developers/Machine-Learning/Object-Recogonition/PointNet/PointNet-v1/sem_seg/point cloud/10F2CM.txt'
    out_data_label_filename = os.path.basename(room_path)[:-4] + '_pred.txt'
    out_data_label_filename = os.path.join(DUMP_DIR, out_data_label_filename)
    print(room_path, out_data_label_filename)
    pred_one_epoch(sess, ops, room_path, out_data_label_filename)
```

```python
def pred_one_epoch(sess, ops, filepath, out_data_label_filename):
    error_cnt = 0
    is_training = False
    total_correct = 0
    total_seen = 0
    loss_sum = 0
    total_seen_class = [0 for _ in range(NUM_CLASSES)]
    total_correct_class = [0 for _ in range(NUM_CLASSES)]
    fout = open(os.path.join(DUMP_DIR, os.path.basename(filepath)[:-4]+'_pred.obj'), 'w')
    fout_data_label = open(out_data_label_filename, 'w')
    
    current_data = room2blocks_wrapper_normalized(filepath, NUM_POINT)
    current_data = current_data[:,0:NUM_POINT,:]
    # Get room dimension..
    data = np.loadtxt(filepath)
    data = data[:,0:6]
    max_room_x = max(data[:,0])
    max_room_y = max(data[:,1])
    max_room_z = max(data[:,2])
    
    file_size = current_data.shape[0]
    num_batches = file_size // BATCH_SIZE
    print(file_size)

    
    for batch_idx in range(num_batches):
        start_idx = batch_idx * BATCH_SIZE
        end_idx = (batch_idx+1) * BATCH_SIZE
        cur_batch_size = end_idx - start_idx
        
        feed_dict = {ops['pointclouds_pl']: current_data[start_idx:end_idx, :, :],
                     ops['is_training_pl']: is_training}
        loss_val, pred_val = sess.run(ops['pred_softmax'],
                                      feed_dict=feed_dict)

        if FLAGS.no_clutter:
            pred_label = np.argmax(pred_val[:,:,0:12], 2) # BxN
        else:
            pred_label = np.argmax(pred_val, 2) # BxN
        # Save prediction labels to OBJ file
        for b in range(BATCH_SIZE):
            pts = current_data[start_idx+b, :, :]
            pts[:,6] *= max_room_x
            pts[:,7] *= max_room_y
            pts[:,8] *= max_room_z
            pts[:,3:6] *= 255.0
            pred = pred_label[b, :]
            for i in range(NUM_POINT):
                color = g_label2color[pred[i]]
                fout.write('v %f %f %f %d %d %d\n' % (pts[i,6], pts[i,7], pts[i,8], color[0], color[1], color[2]))
                fout_data_label.write('%f %f %f %d %d %d %f %d\n' % (pts[i,6], pts[i,7], pts[i,8], pts[i,3], pts[i,4], pts[i,5], pred_val[b,i,pred[i]], pred[i]))

    fout_data_label.close()
    fout.close()
```

### 3.  part modified from [indoor3d_util.py](https://github.com/charlesq34/pointnet/blob/master/sem_seg/indoor3d_util.py)

```python
def room2blocks_wrapper_normalized(data_filename, num_point, block_size=1.0, stride=1.0,
                                   random_sample=False, sample_num=None, sample_aug=1):
    if data_filename[-3:] == 'txt':
        data = np.loadtxt(data_filename)
    elif data_filename[-3:] == 'npy':
        data = np.load(data_filename)
    else:
        print('Unknown file type! exiting.')
        exit()
    return room2blocks_plus_normalized(data, num_point, block_size, stride,
                                       random_sample, sample_num, sample_aug)
```
                                       
```python
def room2blocks_plus_normalized(data, num_point, block_size, stride,
                                random_sample, sample_num, sample_aug):

    data = data[:,0:6]
    data[:,3:6] /= 255.0
    max_room_x = max(data[:,0])
    max_room_y = max(data[:,1])
    max_room_z = max(data[:,2])
    
    data_batch = room2blocks(data, num_point, block_size, stride,
                                          random_sample, sample_num, sample_aug)
    new_data_batch = np.zeros((data_batch.shape[0], num_point, 9))
    for b in range(data_batch.shape[0]):
        new_data_batch[b, :, 6] = data_batch[b, :, 0]/max_room_x
        new_data_batch[b, :, 7] = data_batch[b, :, 1]/max_room_y
        new_data_batch[b, :, 8] = data_batch[b, :, 2]/max_room_z
        minx = min(data_batch[b, :, 0])
        miny = min(data_batch[b, :, 1])
        data_batch[b, :, 0] -= (minx+block_size/2)
        data_batch[b, :, 1] -= (miny+block_size/2)
    new_data_batch[:, :, 0:6] = data_batch
    return new_data_batch
```

```python
def room2blocks(data, num_point, block_size=1.0, stride=1.0,
                random_sample=False, sample_num=None, sample_aug=1):

    assert(stride<=block_size)

    limit = np.amax(data, 0)[0:3]
     
    # Get the corner location for our sampling blocks    
    xbeg_list = []
    ybeg_list = []
    if not random_sample:
        num_block_x = int(np.ceil((limit[0] - block_size) / stride)) + 1
        num_block_y = int(np.ceil((limit[1] - block_size) / stride)) + 1
        for i in range(num_block_x):
            for j in range(num_block_y):
                xbeg_list.append(i*stride)
                ybeg_list.append(j*stride)
    else:
        num_block_x = int(np.ceil(limit[0] / block_size))
        num_block_y = int(np.ceil(limit[1] / block_size))
        if sample_num is None:
            sample_num = num_block_x * num_block_y * sample_aug
        for _ in range(sample_num):
            xbeg = np.random.uniform(-block_size, limit[0]) 
            ybeg = np.random.uniform(-block_size, limit[1]) 
            xbeg_list.append(xbeg)
            ybeg_list.append(ybeg)

    # Collect blocks
    block_data_list = []
    idx = 0
    for idx in range(len(xbeg_list)): 
       xbeg = xbeg_list[idx]
       ybeg = ybeg_list[idx]
       xcond = (data[:,0]<=xbeg+block_size) & (data[:,0]>=xbeg)
       ycond = (data[:,1]<=ybeg+block_size) & (data[:,1]>=ybeg)
       cond = xcond & ycond
       if np.sum(cond) < 100: # discard block if there are less than 100 pts.
           continue
       
       block_data = data[cond, :]
       
       # randomly subsample data
       block_data_sampled = sample_data(block_data, num_point)
       block_data_list.append(np.expand_dims(block_data_sampled, 0))
            
    return np.concatenate(block_data_list, 0)
```

```python
def sample_data(data, num_sample):
    """ data is in N x ...
        we want to keep num_samplexC of them.
        if N > num_sample, we will randomly keep num_sample of them.
        if N < num_sample, we will randomly duplicate samples.
    """
    N = data.shape[0]
    if (N == num_sample):
        return data
    elif (N > num_sample):
        sample = np.random.choice(N, num_sample)
        return data[sample, ...]
    else:
        sample = np.random.choice(N, num_sample-N)
        dup_data = data[sample, ...]
        return np.concatenate([data, dup_data], 0)
```

```python
if __name__=='__main__':
    with tf.Graph().as_default():
        predict()
```

**Comment by RollingIsland** [comment]
Solved. The data need being moved to the coordinate origin.

**Comment by thirdlastletter** [comment]
>     * ### I modified the script as follow to process my own data:
>       
>       1. I use text file as input, not npy file. But the data forms are same in .txt and .npy.
>       2. There is no label for my own data, so those relevant lines in the scripts were deleted.
>          I think these changes should not affect the function of the model, however the result was totally wrong.
> 
>     * ### The form of data like:
> 
> 
> ```
> -0.00650059 49.97880156 -125.81439983 254 254 254
> -0.02650009 49.97840101 -125.81430065 251 251 251
> -0.01760040 49.99639875 -125.81469738 246 246 246
> 0.00240005 49.99739820 -125.81400311 248 248 248
> -0.01719986 49.96049864 -125.81439983 252 252 252
> 0.01370014 49.98089964 -125.81479656 255 255 255
> 0.00600018 49.96239836 -125.81449902 251 251 251
> ```
> 
> The previous 3 columns are **XYZ**, the rest are **RGB (not true color but grey value)**.
> 
>     * ### The seg result is totally wrong:
> 
> 
> ```
> 0.559700 47.716499 -126.147400 139 139 139 1.000000 0
> 0.592000 47.458698 -127.404404 67 67 67 1.000000 0
> 0.013400 47.426899 -126.498901 148 148 148 1.000000 0
> 0.274700 47.592098 -125.803002 200 200 200 1.000000 0
> 0.966400 47.919499 -126.439301 157 157 157 1.000000 0
> 0.876899 47.995201 -128.726700 132 132 132 1.000000 0
> 0.422400 47.648601 -126.555298 85 85 85 1.000000 0
> 0.152500 47.502899 -126.407097 155 155 155 1.000000 0
> ```
> 
> All points were classified as class 0, and the probabilities given were 1.
> Can't figure out the reason.
> 
> ```
>     There's the source code: 
>  ### 1.  const in indoor3d_util.py
> ```
> 
> ```python
> g_classes = [x.rstrip() for x in open(os.path.join(BASE_DIR, 'meta/class_names.txt'))]
> g_class2label = {cls: i for i,cls in enumerate(g_classes)}
> g_class2color = {'ceiling': [0,255,0],
>                  'floor':   [0,0,255],
>                  'wall':    [0,255,255],
>                  'beam':        [255,255,0],
>                  'column':      [255,0,255],
>                  'window':      [100,100,255],
>                  'door':        [200,200,100],
>                  'table':       [170,120,200],
>                  'chair':       [255,0,0],
>                  'sofa':        [200,100,100],
>                  'bookcase':    [10,200,100],
>                  'board':       [200,200,200],
>                  'clutter':     [50,50,50]} 
> g_easy_view_labels = [7,8,9,10,11,1]
> g_label2color = {g_classes.index(cls): g_class2color[cls] for cls in g_classes}
> 
> import argparse
> import os
> import sys
> BASE_DIR = os.path.dirname(os.path.abspath(__file__))
> ROOT_DIR = os.path.dirname(BASE_DIR)
> sys.path.append(BASE_DIR)
> from model import *
> 
> parser = argparse.ArgumentParser()
> parser.add_argument('--gpu', type=int, default=0, help='GPU to use [default: GPU 0]')
> parser.add_argument('--batch_size', type=int, default=1, help='Batch Size during training [default: 1]')
> parser.add_argument('--num_point', type=int, default=4096, help='Point number [default: 4096]')
> parser.add_argument('--model_path', default='log/model.ckpt', help='model checkpoint file path')
> parser.add_argument('--no_clutter', action='store_true', help='If true, donot count the clutter class')
> FLAGS = parser.parse_args()
> 
> BATCH_SIZE = FLAGS.batch_size
> NUM_POINT = FLAGS.num_point
> MODEL_PATH = FLAGS.model_path
> GPU_INDEX = FLAGS.gpu
> DUMP_DIR = 'dump'
> if not os.path.exists(DUMP_DIR):
>     os.mkdir(DUMP_DIR)
> 
> NUM_CLASSES = 13
> ```
> 
> ### 2. part modified from [batch_inference.py](https://github.com/charlesq34/pointnet/blob/master/sem_seg/batch_inference.py)
> 
> ```python
> def predict():
>     is_training = False
>      
>     with tf.device('/gpu:'+str(GPU_INDEX)):
>         pointclouds_pl, labels_pl = placeholder_inputs(BATCH_SIZE, NUM_POINT)
>         is_training_pl = tf.placeholder(tf.bool, shape=())
> 
>         # simple model
>         pred = get_model(pointclouds_pl, is_training_pl)
>         loss = get_loss(pred, labels_pl)
>         pred_softmax = tf.nn.softmax(pred)
>  
>         # Add ops to save and restore all the variables.
>         saver = tf.train.Saver()
>         
>     # Create a session
>     config = tf.ConfigProto()
>     config.gpu_options.allow_growth = True
>     config.allow_soft_placement = True
>     config.log_device_placement = True
>     sess = tf.Session(config=config)
> 
>     # Restore variables from disk.
>     saver.restore(sess, MODEL_PATH)
>     print('  Model restored.')
> 
>     ops = {'pointclouds_pl': pointclouds_pl,
>            'labels_pl': labels_pl,
>            'is_training_pl': is_training_pl,
>            'pred': pred,
>            'pred_softmax': pred_softmax,
>            'loss': loss}
>     
>     total_correct = 0
>     total_seen = 0
>     #room_path = input(' Input point cloud file path: ')
>     room_path = 'E:/Developers/Machine-Learning/Object-Recogonition/PointNet/PointNet-v1/sem_seg/point cloud/10F2CM.txt'
>     out_data_label_filename = os.path.basename(room_path)[:-4] + '_pred.txt'
>     out_data_label_filename = os.path.join(DUMP_DIR, out_data_label_filename)
>     print(room_path, out_data_label_filename)
>     pred_one_epoch(sess, ops, room_path, out_data_label_filename)
> ```
> 
> ```python
> def pred_one_epoch(sess, ops, filepath, out_data_label_filename):
>     error_cnt = 0
>     is_training = False
>     total_correct = 0
>     total_seen = 0
>     loss_sum = 0
>     total_seen_class = [0 for _ in range(NUM_CLASSES)]
>     total_correct_class = [0 for _ in range(NUM_CLASSES)]
>     fout = open(os.path.join(DUMP_DIR, os.path.basename(filepath)[:-4]+'_pred.obj'), 'w')
>     fout_data_label = open(out_data_label_filename, 'w')
>     
>     current_data = room2blocks_wrapper_normalized(filepath, NUM_POINT)
>     current_data = current_data[:,0:NUM_POINT,:]
>     # Get room dimension..
>     data = np.loadtxt(filepath)
>     data = data[:,0:6]
>     max_room_x = max(data[:,0])
>     max_room_y = max(data[:,1])
>     max_room_z = max(data[:,2])
>     
>     file_size = current_data.shape[0]
>     num_batches = file_size // BATCH_SIZE
>     print(file_size)
> 
>     
>     for batch_idx in range(num_batches):
>         start_idx = batch_idx * BATCH_SIZE
>         end_idx = (batch_idx+1) * BATCH_SIZE
>         cur_batch_size = end_idx - start_idx
>         
>         feed_dict = {ops['pointclouds_pl']: current_data[start_idx:end_idx, :, :],
>                      ops['is_training_pl']: is_training}
>         loss_val, pred_val = sess.run(ops['pred_softmax'],
>                                       feed_dict=feed_dict)
> 
>         if FLAGS.no_clutter:
>             pred_label = np.argmax(pred_val[:,:,0:12], 2) # BxN
>         else:
>             pred_label = np.argmax(pred_val, 2) # BxN
>         # Save prediction labels to OBJ file
>         for b in range(BATCH_SIZE):
>             pts = current_data[start_idx+b, :, :]
>             pts[:,6] *= max_room_x
>             pts[:,7] *= max_room_y
>             pts[:,8] *= max_room_z
>             pts[:,3:6] *= 255.0
>             pred = pred_label[b, :]
>             for i in range(NUM_POINT):
>                 color = g_label2color[pred[i]]
>                 fout.write('v %f %f %f %d %d %d\n' % (pts[i,6], pts[i,7], pts[i,8], color[0], color[1], color[2]))
>                 fout_data_label.write('%f %f %f %d %d %d %f %d\n' % (pts[i,6], pts[i,7], pts[i,8], pts[i,3], pts[i,4], pts[i,5], pred_val[b,i,pred[i]], pred[i]))
> 
>     fout_data_label.close()
>     fout.close()
> ```
> 
> ### 3. part modified from [indoor3d_util.py](https://github.com/charlesq34/pointnet/blob/master/sem_seg/indoor3d_util.py)
> 
> ```python
> def room2blocks_wrapper_normalized(data_filename, num_point, block_size=1.0, stride=1.0,
>                                    random_sample=False, sample_num=None, sample_aug=1):
>     if data_filename[-3:] == 'txt':
>         data = np.loadtxt(data_filename)
>     elif data_filename[-3:] == 'npy':
>         data = np.load(data_filename)
>     else:
>         print('Unknown file type! exiting.')
>         exit()
>     return room2blocks_plus_normalized(data, num_point, block_size, stride,
>                                        random_sample, sample_num, sample_aug)
> ```
> 
> ```python
> def room2blocks_plus_normalized(data, num_point, block_size, stride,
>                                 random_sample, sample_num, sample_aug):
> 
>     data = data[:,0:6]
>     data[:,3:6] /= 255.0
>     max_room_x = max(data[:,0])
>     max_room_y = max(data[:,1])
>     max_room_z = max(data[:,2])
>     
>     data_batch = room2blocks(data, num_point, block_size, stride,
>                                           random_sample, sample_num, sample_aug)
>     new_data_batch = np.zeros((data_batch.shape[0], num_point, 9))
>     for b in range(data_batch.shape[0]):
>         new_data_batch[b, :, 6] = data_batch[b, :, 0]/max_room_x
>         new_data_batch[b, :, 7] = data_batch[b, :, 1]/max_room_y
>         new_data_batch[b, :, 8] = data_batch[b, :, 2]/max_room_z
>         minx = min(data_batch[b, :, 0])
>         miny = min(data_batch[b, :, 1])
>         data_batch[b, :, 0] -= (minx+block_size/2)
>         data_batch[b, :, 1] -= (miny+block_size/2)
>     new_data_batch[:, :, 0:6] = data_batch
>     return new_data_batch
> ```
> 
> ```python
> def room2blocks(data, num_point, block_size=1.0, stride=1.0,
>                 random_sample=False, sample_num=None, sample_aug=1):
> 
>     assert(stride<=block_size)
> 
>     limit = np.amax(data, 0)[0:3]
>      
>     # Get the corner location for our sampling blocks    
>     xbeg_list = []
>     ybeg_list = []
>     if not random_sample:
>         num_block_x = int(np.ceil((limit[0] - block_size) / stride)) + 1
>         num_block_y = int(np.ceil((limit[1] - block_size) / stride)) + 1
>         for i in range(num_block_x):
>             for j in range(num_block_y):
>                 xbeg_list.append(i*stride)
>                 ybeg_list.append(j*stride)
>     else:
>         num_block_x = int(np.ceil(limit[0] / block_size))
>         num_block_y = int(np.ceil(limit[1] / block_size))
>         if sample_num is None:
>             sample_num = num_block_x * num_block_y * sample_aug
>         for _ in range(sample_num):
>             xbeg = np.random.uniform(-block_size, limit[0]) 
>             ybeg = np.random.uniform(-block_size, limit[1]) 
>             xbeg_list.append(xbeg)
>             ybeg_list.append(ybeg)
> 
>     # Collect blocks
>     block_data_list = []
>     idx = 0
>     for idx in range(len(xbeg_list)): 
>        xbeg = xbeg_list[idx]
>        ybeg = ybeg_list[idx]
>        xcond = (data[:,0]<=xbeg+block_size) & (data[:,0]>=xbeg)
>        ycond = (data[:,1]<=ybeg+block_size) & (data[:,1]>=ybeg)
>        cond = xcond & ycond
>        if np.sum(cond) < 100: # discard block if there are less than 100 pts.
>            continue
>        
>        block_data = data[cond, :]
>        
>        # randomly subsample data
>        block_data_sampled = sample_data(block_data, num_point)
>        block_data_list.append(np.expand_dims(block_data_sampled, 0))
>             
>     return np.concatenate(block_data_list, 0)
> ```
> 
> ```python
> def sample_data(data, num_sample):
>     """ data is in N x ...
>         we want to keep num_samplexC of them.
>         if N > num_sample, we will randomly keep num_sample of them.
>         if N < num_sample, we will randomly duplicate samples.
>     """
>     N = data.shape[0]
>     if (N == num_sample):
>         return data
>     elif (N > num_sample):
>         sample = np.random.choice(N, num_sample)
>         return data[sample, ...]
>     else:
>         sample = np.random.choice(N, num_sample-N)
>         dup_data = data[sample, ...]
>         return np.concatenate([data, dup_data], 0)
> ```
> 
> ```python
> if __name__=='__main__':
>     with tf.Graph().as_default():
>         predict()
> ```

Hi,
how did you get to the sem seg results? Or more specifically how do you display them with all the files that are created after training?
Thank you!

**Comment by RollingIsland** [comment]
@thirdlastletter 
#167 
I followed the step in issue 167 to display the .obj files. Hope it will be help.

**Comment by thirdlastletter** [comment]
> @thirdlastletter
> #167
> I followed the step in issue 167 to display the .obj files. Hope it will be help.

Thank you! I get it now.

I am yet unsure how to predict data after training. Training on my dataset works, but how do I use PointNet to predict segmentation on new data?

**Comment by RollingIsland** [comment]
@thirdlastletter 
Well, function "evaluate" and "eval_one_epoch" in "batch_inference.py" are the main part of predicting. You need to change the file path to your own and make sure the coordinates in your data starting from (0, 0, 0) (and remember to remove isolated points).
I have already shown the modification need be done in this issue.

**Comment by thirdlastletter** [comment]
> @thirdlastletter
> Well, function "evaluate" and "eval_one_epoch" in "batch_inference.py" are the main part of predicting. You need to change the file path to your own and make sure the coordinates in your data starting from (0, 0, 0) (and remember to remove isolated points).
> I have already shown the modification need be done in this issue.

ok thank you! That part I understand now. What I am still unsure is what you mean with "move the data to coordinate origin". I can't just use my data?

**Comment by RollingIsland** [comment]
@thirdlastletter 
Of course you can use your own data directly! But the coordinates in training data start from 0, so if the minimum of coordinates is far from 0, the prediction will be bad, such as all points were predicted as floor or ceiling.

**Comment by RollingIsland** [comment]
@thirdlastletter 
And hope you can delete the quote in your first reply, the long code makes it hard to pull to the bottom. :-)

**Comment by thirdlastletter** [comment]
@RollingIsland I deleted it :)

So basically if I use a whole set of data that is different from the sample data anyway for training I can just use similar data for the testing too right? without needing to shift anything?

**Comment by RollingIsland** [comment]
@thirdlastletter 
Theoretically you are right. But I have never tried because lack of labeled data. You can do a trial.

**Comment by thirdlastletter** [comment]
@RollingIsland ok thanks for the help :) I will try this

**Comment by STARBOYsachin** [comment]
@thirdlastletter 

> @RollingIsland I deleted it :)
> 
> So basically if I use a whole set of data that is different from the sample data anyway for training I can just use similar data for the testing too right? without needing to shift anything?

Is it successful using own data?

**Comment by euzer** [comment]
Hi there,
I need to apply PointNet on my own data, but i don't know how to do it. I mean how to annotate my data in order to produce some txt, npy files. 
Thanks !

**Comment by RollingIsland** [comment]
@Naor92 
I suppose your problem is because some of your point coordinates are negative. I'm not so sure for I've been away from this project a while.
And I suggest you to check your pointclouds to make sure there is no single point which is far away from your point set. I use Matlab to modify the file. It's easy to find if there any single point by drawing charts of coordinates.

**Comment by Naor92** [comment]
@RollingIsland 

Thanks for the response! I’m going to look into how I can solve the issue with the negative points, will give Matlab a try.

**Comment by Tojens** [comment]
I am having the same problems as posted by you. Could you perhaps create a repo showing some of the changes you did? I'd be interested in seeing them :)

Thanks in advance!

**Comment by AmarR91** [comment]
@RollingIsland  I would also appreciate if you could share your edited script with us. I don't understand how to change the script in order to use my own dataset for the segmenation process.

**Comment by RollingIsland** [comment]
> Well, function "evaluate" and "eval_one_epoch" in "batch_inference.py" are the main part of predicting. You need to change the file path to your own and make sure the coordinates in your data starting from (0, 0, 0) (and remember to remove isolated points).
> I have already shown the modification need be done in this issue.

@AmarR91 
The changes I made to the script are as mentioned above. The model can be directly used for segmentation if the coordinates of your data are positive and near the origin (0,0,0), just  as the sample data. 
Sorry I have no copy of the modified script, since I've been away from this project too long.

**Comment by fahome10bd** [comment]
> * ### I modified the script as follow to process my own data:
>   
>   1. I use text file as input, not npy file. But the data forms are same in .txt and .npy.
>   2. There is no label for my own data, so those relevant lines in the scripts were deleted.
>      I think these changes should not affect the function of the model, however the result was totally wrong.
> * ### The form of data like:
> 
> ```
> -0.00650059 49.97880156 -125.81439983 254 254 254
> -0.02650009 49.97840101 -125.81430065 251 251 251
> -0.01760040 49.99639875 -125.81469738 246 246 246
> 0.00240005 49.99739820 -125.81400311 248 248 248
> -0.01719986 49.96049864 -125.81439983 252 252 252
> 0.01370014 49.98089964 -125.81479656 255 255 255
> 0.00600018 49.96239836 -125.81449902 251 251 251
> ```
> 
> The previous 3 columns are **XYZ**, the rest are **RGB (not true color but grey value)**.
> 
> * ### The seg result is totally wrong:
> 
> ```
> 0.559700 47.716499 -126.147400 139 139 139 1.000000 0
> 0.592000 47.458698 -127.404404 67 67 67 1.000000 0
> 0.013400 47.426899 -126.498901 148 148 148 1.000000 0
> 0.274700 47.592098 -125.803002 200 200 200 1.000000 0
> 0.966400 47.919499 -126.439301 157 157 157 1.000000 0
> 0.876899 47.995201 -128.726700 132 132 132 1.000000 0
> 0.422400 47.648601 -126.555298 85 85 85 1.000000 0
> 0.152500 47.502899 -126.407097 155 155 155 1.000000 0
> ```
> 
> All points were classified as class 0, and the probabilities given were 1.
> Can't figure out the reason.

Can you share your modified code for predicting your own dataset?
I have my model ready to predict and my data as .txt file but this repo has no code for detect the dataset using model.
