### ISSUE TITLE
Semantic Segmentation issue.

### ISSUE THREAD

**Issue by wshilin** [charlesq34/pointnet#19]
I use   **sh download_data.sh**     to download dataset.
Then use    **python collect_indoor3d_data.py**.But it appears a problem that I don't know how to deal with (As the picture shows below).
![img_5554](https://user-images.githubusercontent.com/4417111/27676525-e160ce46-5ce0-11e7-8e8a-09db95f13787.JPG)

**Comment by charlesq34** [comment]
@wshilin Have you downloaded the data?

**Comment by biao187** [comment]
I have the same problem,and i have downloaded the data, have you solve the problem ?@wshilin

**Comment by wshilin** [comment]
The data path you unzip the data to is not correct.

**Comment by wshilin** [comment]
The data path you unzip the data to is not correct.




On 1/18/2018 16:32，biao187<notifications@github.com> wrote：

I have the same problem,and i have downloaded the data, have you solve the problem ?@wshilin

**Comment by PRAhit** [comment]
i think you have to set the path of downloaded 3D indoor parsing dataset in indoor3d_util.py with the same unzip file name (Stanford3dDataset_v1.2 --> in my case) then try to run collect_indoor3d_data.py. Cheers.

**Comment by mescpla** [comment]
Hey there, I have this same issue.

As I've read, I changed the name of the file inside indoor3d_util.py, but I still get this error.

![2654](https://user-images.githubusercontent.com/37616549/40420160-b17f601c-5e87-11e8-8c0f-89d4aa717254.jpeg)

My  dowloaded data (which automatic unzips), is called "indoor3d_sem_seg_hdf5_data" and it is inside the sem_seg folder

I tried to change 'Stanford3dDataset_v1.2_Aligned_Version' for "indoor3d_sem_seg_hdf5_data" and it didn't work. I tried to move the data folder all around: to the ROOT_DIR, to the BASE_DIR, to a folder called data inside the ROOT_DIR, and after that the BASE_DIR ....

I don't know what am I missing. Any help please? 
= /
