### ISSUE TITLE
Pointnet using my own data

### ISSUE THREAD

**Issue by JavierRubioR** [charlesq34/pointnet#198]
Hi, I am trying to use pointnet as classifier with my own dataset. The training steps seem to go without problems but I am facing the following error when I run the evaluate.py script:

![pointneterror](https://user-images.githubusercontent.com/50619838/64740695-1ae48680-d4ee-11e9-9b86-83c8dddceb4a.png)

I am not changing anything in the code but the paths to my own files (shape_names.txt, train_files.txt and test_files.txt) and the value of the NUM_CLASSES variable. [Here](https://drive.google.com/open?id=1L88r39OrKpeAqQOfF-YYK0XRYwSuZDoN) are the train and test datasets I am using. Could you please help me to solve this issue?

Regards,
Javier.

**Comment by charlesq34** [comment]
It seems you also have to change the number of output classes in the model file (`pointnet.py`). In default it is 40.
