### ISSUE TITLE
Typo error in parameter name in utils/data_prep_util.py

### ISSUE THREAD

**Issue by arunumd** [charlesq34/pointnet#199]
![issue pointnet](https://user-images.githubusercontent.com/32076623/65266059-4d8b1200-dae0-11e9-8aed-a4f266e69b60.PNG)

In line no 61 from the _utils/data_prep_util.py_ file shown above, the function parameter name is _noral_dtype_. Whereas inside the function, this parameter is referenced with a different name _normal_dtype._ This appears to be a typo error and is likely to give issues while trying to run this function. 

**Suggestion:**
May be the names should be consistent in function parameter and while referencing.

**Comment by charlesq34** [comment]
Thanks for pointing it out. Fixed now!
