### ISSUE TITLE
some questions about code

### ISSUE THREAD

**Issue by legendhua** [charlesq34/pointnet#2]
Dear Mr./Ms,
I am a graduate student from XDU. My project is about Deep Learning. I am writing to asking you sth about your paper PointNet. Here is the problem
I have achieved the part of the training and testing of 3D object classification before i ask you, thanks for your codes. Now i want to understanding what the network has learnt for next step, so would you tell me how to achieve visualization or what should i do.
I am appreciated if you can give us the code about segmentation and other experiments.
Looking forward to hearing from you, and thank you for the help in advance.
Best regards,
Zhang GH.

**Comment by daerduoCarey** [comment]
We've just updated our code for part segmentation. Please check part_seg folder. For the visualization code, we will update them later. The methods to generate the visualization that are presented in the paper are clearly stated in the paper and the appendix. Please refer to the paper before we clean up and release our code. Thank you.

**Comment by legendhua** [comment]
Thanks for your reply and your code.
