### ISSUE TITLE
Semantic Segmentation of own data - Parts of cloud disappears?

### ISSUE THREAD

**Issue by Naor92** [charlesq34/pointnet#201]
Hey guys, so I've successfully been able to segment a point cloud of my living room by training my model using the provided 3D indoor parsing dataset. Here is a picture of the old result:

![2019-08-01](https://user-images.githubusercontent.com/26039559/65708389-7d946100-e05c-11e9-98ff-efd1e5e455d0.jpeg)

I don't know what could have possibly changed but now running batch_inference seems to cut out half the points of the cloud and not running the segmentation correctly. Like this:

![Screenshot from 2019-09-26 12-45-58](https://user-images.githubusercontent.com/26039559/65708670-23e06680-e05d-11e9-9b65-36f2dbb8f04a.png)

Anyone have a clue what could be causing that behavior? I even reran the training and got decent accuracy results but no change when trying to segment my own point clouds.

**Comment by discretecoder** [comment]
How did you infer? just with XYZ and not with XYZRGBL format?

**Comment by Naor92** [comment]
I used just XYZRGB format. I was using Kinects not Lidar
