### ISSUE TITLE
Unable to convert pcd files to h5 files

### ISSUE THREAD

**Issue by arunumd** [charlesq34/pointnet#204]
I have many .ply files (generated pcd files from rosbag and then converted the pcd files to ply files using pcl_pcd2ply command). I am using plyfile API to read ply files and then convert them into numpy arrays of X * 2048 * 3 dimension. But the ply file generated by pcl_pcd2ply seems to have some duplicate properties and hence could not be opened by plyFile API. Can anybody suggested an effective method to open point cloud data in the form of pcd files for h5 file preparation ?

**Comment by lyy-1997-hub** [comment]
Hi, did you succeed?
