### ISSUE TITLE
Detection pipeline for scene segmentation

### ISSUE THREAD

**Issue by ashishk008** [charlesq34/pointnet#21]
Hi Charles,
     How exactly are you building the graph for BFS search to get the connected components in the detection pipeline? I could not find the code for detection pipeline in the repo. Are you planning to add it in near future? Thanks.

**Comment by charlesq34** [comment]
Hi @ashishk008 

I randomly select a point as seed point and try to find connected component. When no more points within a certain radius can be found, I will select a new seed point from the remaining points and repeat the process.

There is currently no plan to release that code. Hopefully someone will build a more robust 3D object detector upon current framework
