### ISSUE TITLE
How to use batch inference file to get inference from my own labeled data?

### ISSUE THREAD

**Issue by morimkb** [charlesq34/pointnet#211]
Hello,

I have segmented a scene file and it is saved as a .txt file and structured like this:
XYZRGBL
I would like to get inference from this file and see the model results.
I know that I have to change some paths and I have done that, but still the batch_inference.py is using other utils that they use other data paths for annotations and preparation of normalized .npy files. I guess this process is so complicated for just getting a simple inference from a trained model. Is there any way to make this process simpler or has anyone made a file for it?

**Comment by morimkb** [comment]
I have found how to do it, so I close the issue.

**Comment by Tojens** [comment]
I am having the same issue. Could you tell me what you did to get it to work?

Best regards, Tobias
