### ISSUE TITLE
Question about FLOPs/sample

### ISSUE THREAD

**Issue by Xiangxu-0103** [charlesq34/pointnet#216]
Hi
     I'm trying to calculate the FLOPs/sample you mentioned in the paper, but it has a large difference with the result you reported.
Here is my code! Wish your reply!
![1](https://user-images.githubusercontent.com/55445986/68013255-6550db00-fcc7-11e9-9665-f5f92380a370.jpg)

**Comment by WuzhaoLee** [comment]
Hello, I have this question, too. I use the same code as yours, then I calculate the FLOPs/sample as: 899521486, (about twice the results in the paper) and params as 3480049. (The model is 'pointnet_cls.py').  What about your calculation results?

**Comment by Xiangxu-0103** [comment]
Hi:
  I'm so sorry to respond to your message so long. The FLOPs reported in
PointNet is float op per SAMPLE and didn't include BN etc. op.
  Best wishes.
Xiang.

WuzhaoLi <notifications@github.com> 于2020年1月3日周五 下午4:47写道：
