### ISSUE TITLE
object segmentaion

### ISSUE THREAD

**Issue by JordLee** [charlesq34/pointnet#22]
Hello Charles,

I am trying to use raw point cloud data(pcd file format). My goal is to segment random object from the table top scene.
How can I process the data set and visualize(view) the point cloud data which is segmented?
Thank you in advanced!

**Comment by charlesq34** [comment]
Hi @JordLee 

Do you have some training data to train the network?
or you can actually synthesize some with Blensor, you can select some table models and random object models and synthesize training data for segmentation. Or a plane detector will also help to detect the table surface. 

You can dump prediction use MeshLab to view it.
