### ISSUE TITLE
sem_seg testing issue

### ISSUE THREAD

**Issue by wshilin** [charlesq34/pointnet#23]
Hello Charles,
Arter training,I follow the instruction about testing in README.md of sem_seg folder.But as you can see below,there is an error .
![img_5644 20170714-093438](https://user-images.githubusercontent.com/4417111/28194741-e1870d9c-6878-11e7-9f3a-406cacaaff16.jpg)

**Comment by charlesq34** [comment]
Hi @wshilin  I think --modle_path should be --model_path.. it's a typo
