### ISSUE TITLE
How to prepare outdoor point cloud data for classification using deep learning?

### ISSUE THREAD

**Issue by anniepapalexiou** [charlesq34/pointnet#256]
My data are lidar point clouds from a railway environment. I want to classify them into 6 classes (rails, sleepers, wires and so on) using DGCNN. I now have 1 las file for each class. However, these h5 files used as inputs in the model seem to be more suitable for indoor data. I suppose that I should split my data into blocks of let's say 1m x 1m, subsample each class within this block with the same number of points and pass each of them as a row in the h5 file. But I am not sure how to implement that. Also it would be nice if there was a way to directly give lidar data to the model as input.

**Comment by cystal-lili** [comment]
Hello, can you talk about it? I'm also running this model
