### ISSUE TITLE
How much GPU memory needed for training a sem segment model?

### ISSUE THREAD

**Issue by ZhaozhengPlus** [charlesq34/pointnet#26]
I have used a 4G memory GPU  to train a part and segment model, but it out of memory , how much memory it needs? And it is possible for me to use a 4G Gpu by reduce the Neuron？

**Comment by charlesq34** [comment]
I think it depends on batch size, could you try to reduce batch size to 1 or 2 and see if it works?

**Comment by charlesq34** [comment]
Hi @ZhaozhengPlus 

4GB should be enough if you cut the neuron numbers and input point number by half and reduce batch size to 4.

**Comment by ZhaozhengPlus** [comment]
Hi, @charlesq34 

 It works, thanks very much!
