### ISSUE TITLE
error when i run python gen_indoor3d_h5.py

### ISSUE THREAD

**Issue by ZhaozhengPlus** [charlesq34/pointnet#29]
my python version is 2.7, when I run the command :python gen_indoor3d_h5.py to test the sem_segmention, it occurs error as follows:

![screenshot from 2017-07-21 18-29-19](https://user-images.githubusercontent.com/18107059/28460091-0b589ff8-6e43-11e7-8de2-e96b77a8a57a.png)

**Comment by adrianloy** [comment]
I had the same error when trying to apply the semantic segmentation part on own data. The reason for it was that multiple files with the same name from different directories were tried to be packed into the same hd5 file. Renaming the files with duplicate names solved the issue for me.

**Comment by ZhaozhengPlus** [comment]
@adrianloy 

 It's helpful! Thank you very much!
