### ISSUE TITLE
How much memory needed for sem_seg training

### ISSUE THREAD

**Issue by AbdouBou** [charlesq34/pointnet#302]
I'm trying to train the sem_seg model as indicated in the read-me file.

I'm getting a "Stopped process" indication. At the same time i can see that it occurs exacty when the RAM is full on the monitor.

My question is how much RAM is needed for training without RAM limitation. and where to set a RAM limitation if possible?

**Comment by rohithsaro** [comment]
Hi @AbdouBou 
When using the GPU for training it takes up at least 10 GB.
However you can try reducing the the batch size according to your specifications. It should be fine after that.

Best,

Rohith

**Comment by AbdouBou** [comment]
Hi @rohithsaro 
Ok, thank you for answering.
