### ISSUE TITLE
Network architecture inconsistent with paper

### ISSUE THREAD

**Issue by shangyouai** [charlesq34/pointnet#31]
hello, in your paper, supplementary C it says:

> As to semantic segmentation task, we used the architecture as in Fig 2 in the main paper.

but in pointnet/sem_seg/model.py, get_model function, I found some inconsistency such as there is no T-Net implemented, and the concatenated  layer comes from another two layer instead of the layers marked by dotted arrow of Fig 2. Is this a mistake or i got something wrong?

by the way , I want to ask that how did you came up the idea of T-Net? Is there any reason about that?  Is the T-Net in relation to some rigid transformation of the point cloud? Because it seems like a magic to me.

**Comment by charlesq34** [comment]
Hi @shangyouai 

Thanks for pointing that out! We found that T-net doesn't help much for this specific task so it's not included in the released code. The concatenation from 1024-dim feature seems result in slightly better performance -- it is slightly different from Fig. 2 as you pointed out. We shall correct that sentence if we would update the paper on ArXiv.

The T-net idea originates from Spatial Transformer Network (https://arxiv.org/abs/1506.02025), if you have known that it will become very natural. The benefits of using transformer network on point cloud is that the transformation computation is very simple and flexible -- it's just a matrix multiplication (in images or voxels you need to do bilinear or trilinear sampling).

Hope it helps. Let me know if you have more questions.

**Comment by charlesq34** [comment]
i'm closing the thread since no new comment comes.
