### ISSUE TITLE
Recognize bottle from ycb data as monitor!

### ISSUE THREAD

**Issue by mzaiady** [charlesq34/pointnet#33]
hi..
I'm trying to use pointnet to recognize object from ycb dataset (http://www.ycbbenchmarks.com/)  under the  category of bottle, and it does have very similar shape to training dataset, but point-net did not recognize it correctly! I think the issue may be related to how I prepare/down-sample  the data!

I tried with the 006_mustard_bottle.ply, it contains  847289 point, down-sampled it randomly to 1024 point:

![image](https://user-images.githubusercontent.com/1568843/29121141-5f1f5566-7d1e-11e7-9940-aaf2160dfed9.png)

result in  following:

![image](https://user-images.githubusercontent.com/1568843/29120552-ca9cd302-7d1b-11e7-88be-a8b7647b4433.png)

![image](https://user-images.githubusercontent.com/1568843/29120560-d50a8bea-7d1b-11e7-9651-8f40e02103bf.png)

The classification result was :

irplane = -10065.7
bathtub = -10174.7
bed = -5508.48
bench = -6663.82
bookshelf = -7400.75
bottle = -15664.8
bowl = -6521.66
car = -14696.8
chair = -11587.8
cone = -8178.83
cup = -13763.6
curtain = -4454.49
desk = -19952.4
door = -12188.9
dresser = -4633.64
flower_pot = 1036.69
glass_box = -7719.06
guitar = -8977.43
keyboard = -15161.3
lamp = -5138.02
laptop = -6836.96
mantel = -13274.9
monitor = -9731.3
night_stand = -11224.4
person = -16864.7
piano = -17242.8
plant = 1167.26
**radio = 1352.54**
range_hood = -13157.3
sink = -9762.18
sofa = -18294.6
stairs = -5749.73
stool = -10743.8
table = -6021.3
tent = -11153.3
toilet = -10596.6
tv_stand = -3238.71
vase = -7211.66
wardrobe = -13034.5
xbox = -6992.64

I tried different approach, by voxlize to get better result:

![image](https://user-images.githubusercontent.com/1568843/29120693-91cb177c-7d1c-11e7-99d5-4783f3ac221b.png)

![image](https://user-images.githubusercontent.com/1568843/29120701-982a1762-7d1c-11e7-93e9-83424acafa50.png)

loss value 13.4148

airplane = -9.70358
bathtub = -19.6874
bed = -13.8628
bench = -15.0484
bookshelf = -14.7929
bottle = -10.4973
bowl = -14.3144
car = -7.3393
chair = -12.6577
cone = -8.53707
cup = -7.65949
curtain = -19.0757
desk = -16.9046
door = -20.5851
dresser = -8.47661
flower_pot = 1.46643
glass_box = -15.3492
guitar = -12.4239
keyboard = -20.1066
lamp = -8.02352
laptop = -17.523
mantel = -13.7787
**monitor = 2.63108**
night_stand = -6.75316
person = -11.2164
piano = -3.55436
plant = -2.09806
radio = -3.64729
range_hood = -14.5621
sink = -10.3373
sofa = -14.9684
stairs = -3.0044
stool = -14.2689
table = -19.0393
tent = -3.54769
toilet = -4.67468
tv_stand = -15.6987
vase = -5.87417
wardrobe = -15.3384
xbox = -11.0024
 
What is the best approach to prepare data to get  more accurate results?

**Comment by charlesq34** [comment]
hi @mzaiady 

did you use YCB data for training as well?
data preprocessing does matter a lot, have you normalized the XYZ coordinates of the point cloud?
in ModelNet40 training we made the point cloud zero mean and be within a unit sphere. btw, is the point cloud partial or complete?

**Comment by mzaiady** [comment]
I did not use ycb for training, but object structure and dimensions are similar to those on  ModelNet! my though that network should able recognize objects of the same category (e.g. bottle) without seeing exact one before!

for preprocessing I used the following code from  pointnet/utils/pc_util.py

>         centroid = np.mean(points, axis=0)
>         points -= centroid
>         furthest_distance = np.max(np.sqrt(np.sum(abs(points)**2,axis=-1)))
>         points /= furthest_distance

For ycb data, point cloud are complete, but to which degree cloud it support partial view of point cloud!

**Comment by charlesq34** [comment]
Hi @mzaiady  Have aligned the XYZ coordinates?
It looks to me that the Z axis is not the up direction in the visualization figure

**Comment by charlesq34** [comment]
I'm closing the issues since there is no further response. Will reopen it if necessary.

**Comment by zhangcogito** [comment]
> hi..
> I'm trying to use pointnet to recognize object from ycb dataset (http://www.ycbbenchmarks.com/) under the category of bottle, and it does have very similar shape to training dataset, but point-net did not recognize it correctly! I think the issue may be related to how I prepare/down-sample the data!
> 
> I tried with the 006_mustard_bottle.ply, it contains 847289 point, down-sampled it randomly to 1024 point:
> 
> ![image](https://user-images.githubusercontent.com/1568843/29121141-5f1f5566-7d1e-11e7-9940-aaf2160dfed9.png)
> 
> result in following:
> 
> ![image](https://user-images.githubusercontent.com/1568843/29120552-ca9cd302-7d1b-11e7-88be-a8b7647b4433.png)
> 
> ![image](https://user-images.githubusercontent.com/1568843/29120560-d50a8bea-7d1b-11e7-9651-8f40e02103bf.png)
> 
> The classification result was :
> 
> irplane = -10065.7
> bathtub = -10174.7
> bed = -5508.48
> bench = -6663.82
> bookshelf = -7400.75
> bottle = -15664.8
> bowl = -6521.66
> car = -14696.8
> chair = -11587.8
> cone = -8178.83
> cup = -13763.6
> curtain = -4454.49
> desk = -19952.4
> door = -12188.9
> dresser = -4633.64
> flower_pot = 1036.69
> glass_box = -7719.06
> guitar = -8977.43
> keyboard = -15161.3
> lamp = -5138.02
> laptop = -6836.96
> mantel = -13274.9
> monitor = -9731.3
> night_stand = -11224.4
> person = -16864.7
> piano = -17242.8
> plant = 1167.26
> **radio = 1352.54**
> range_hood = -13157.3
> sink = -9762.18
> sofa = -18294.6
> stairs = -5749.73
> stool = -10743.8
> table = -6021.3
> tent = -11153.3
> toilet = -10596.6
> tv_stand = -3238.71
> vase = -7211.66
> wardrobe = -13034.5
> xbox = -6992.64
> 
> I tried different approach, by voxlize to get better result:
> 
> ![image](https://user-images.githubusercontent.com/1568843/29120693-91cb177c-7d1c-11e7-99d5-4783f3ac221b.png)
> 
> ![image](https://user-images.githubusercontent.com/1568843/29120701-982a1762-7d1c-11e7-93e9-83424acafa50.png)
> 
> loss value 13.4148
> 
> airplane = -9.70358
> bathtub = -19.6874
> bed = -13.8628
> bench = -15.0484
> bookshelf = -14.7929
> bottle = -10.4973
> bowl = -14.3144
> car = -7.3393
> chair = -12.6577
> cone = -8.53707
> cup = -7.65949
> curtain = -19.0757
> desk = -16.9046
> door = -20.5851
> dresser = -8.47661
> flower_pot = 1.46643
> glass_box = -15.3492
> guitar = -12.4239
> keyboard = -20.1066
> lamp = -8.02352
> laptop = -17.523
> mantel = -13.7787
> **monitor = 2.63108**
> night_stand = -6.75316
> person = -11.2164
> piano = -3.55436
> plant = -2.09806
> radio = -3.64729
> range_hood = -14.5621
> sink = -10.3373
> sofa = -14.9684
> stairs = -3.0044
> stool = -14.2689
> table = -19.0393
> tent = -3.54769
> toilet = -4.67468
> tv_stand = -15.6987
> vase = -5.87417
> wardrobe = -15.3384
> xbox = -11.0024
> 
> What is the best approach to prepare data to get more accurate results?

Hi,
I also encounter the problem. I tried to recognize objects from ycb dataset.  But all the objects are
recognized as guitar, lamp, cone or person. Have you resolved it?
