### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by innfarn** [charlesq34/pointnet#36]
Hello,

I tried to use PointNet in Windows, but it's failed to run in below two lines:
-------------------------------------------------------------------
os.system('cp %s %s' % (MODEL_FILE, LOG_DIR)) # bkp of model def
os.system('cp train.py %s' % (LOG_DIR)) # bkp of train procedure
-------------------------------------------------------------------

So I changed os.system function calls to shutil's copy2 function.
-------------------------------------------------------------------
import shutil
shutil.copy2(MODEL_FILE, LOG_DIR)
shutil.copy2('train.py', LOG_DIR)
-------------------------------------------------------------------

After that, it's working nicely in windows.

BTW, great work!

**Comment by charlesq34** [comment]
Great! Those two lines are calling linux system functions.. the shutil is more environment agnostic.
