### ISSUE TITLE
What would be the optimised nn layer num_output_channels for 8192 points?

### ISSUE THREAD

**Issue by Karthik777** [charlesq34/pointnet#4]
Hi Charles,
I'm training pointnet with 8192 points per cloud. Should the neural net tensors be modified to a specific size. i.e Currently the nn's output channles are 64 output (1,3) stride ,64(1,1),128(1,1),1024 and these are optimised for a max of 2048 points I guess.
What would be the optimised nn layer num_output_channels for 8192 points?

**Comment by daerduoCarey** [comment]
Hi, thank you for your interests in our paper. First, it's not guaranteed that our setting provides the best performance for 2048 points. It is really hard to globally guarantee anything in neural network training. But we have tried our best and this setting provides the best among our trials. Second, for your 8192 case, sadly we haven't fine-tuned for this case thus it is hard for us to provide the best optimized setting. But we indeed performed some experiment showing that increasing the point number exceeding some number (i.e. 2048, 4096 and higher) does not improve the final classification performance so much. Hope you can try on your case and report your best results to use. We appreciate it very much! Thank you.

**Comment by charlesq34** [comment]
Generally I would suggest try increase the bottleneck size 1024. But as Kaichun said, it's hard to say without experiments for your specific data and task.

**Comment by Karthik777** [comment]
I've tried increasing the kernel size and the training is still running. will also run a separate test with changing the the window size and report back.
