### ISSUE TITLE
pointnet/part_seg/

### ISSUE THREAD

**Issue by lfs119** [charlesq34/pointnet#40]
Hi,I have trained segmentation network with default batch size 32,point number 2048,epoch 50,However .Test's Iou is 83.00 lower than 83.7 as shown in paper,Is there some advance to enhance it to correspond with 83.7 or reasons resulted in lower Iou.
Thanks

**Comment by daerduoCarey** [comment]
I think 83.0 is comparable with 83.7 in number, so you are almost there.
There are so many tricks to tune neural networks. Are you using the exactly same code we released? Try to train for more epochs and use object category information, the later one helps a lot.

Thanks.
Kaichun
