### ISSUE TITLE
Could this code be modified for flexible number of points

### ISSUE THREAD

**Issue by JimmyCai91** [charlesq34/pointnet#41]
Hi Charles, thanks for sharing such a nice implementation. I have a question that if we can have this code modified so that is can takes points with flexible size. For example to claim the pointclouds placeholder as:
pointclouds_pl = tf.placeholder(tf.float32, shape=(batch_size, None, 3))

However, it reports error during graph building,

num_point = pointclouds_pl.get_shape()[1].value
net = tf_util.max_pool2d(net, [num_point,1], padding='VALID', scope='maxpool')

TypeError: Expected int for argument 'ksize' not None.

==== add by Sep. 3 ====
This error is from tf.nn.max_pool, which requires kernel size should not be None. A direct solution could be create a new operation layer in place of tf.nn.max_pool.

**Comment by daerduoCarey** [comment]
yes, definitely you can do that. But in most of our cases, the point number for point cloud in a training batch does not vary too much. So we can just make the point number the same by repeating the last points for the point clouds with not enough point and resampling for the point clouds with too much points.

You're very welcomed to file a pull request if you implement the max_pool layer with changable kernel size.

Thanks.
Kaichun

**Comment by EndingCredits** [comment]
`tf.reduce_max` could be used instead, although it's possible there may be a bit of a performance penalty.

**Comment by charlesq34** [comment]
Hi @JimmyCai91, @EndingCredits 

you can replace max pooling layer code: 
`net = tf_util.max_pool2d(net, [num_point,1], padding='VALID', scope='maxpool')`

by 
`net = tf.reduce_max(net, axis=[1,2])`

and it will just work. But still you have to use same number of points in each batch.
hope it helps
