### ISSUE TITLE
pointnet++

### ISSUE THREAD

**Issue by mf27** [charlesq34/pointnet#43]
I'm interested in your follow-up work - the improved Pointnet (Pointnet++).

To me it's not totally clear how exactly you applied (vanilla) Pointnet after data grouping stage - namely, what was the value of parameter C' (length of the feature vector for every group) in your paper?

For example, the notation SA(512, 0.2, [64, 64, 128]) - how exactly does the explanation of PointNet layer in Section 3.2 fit here? What is the exact size of the input to the PointNet (after sampling and grouping stage), and the output?

Thanks!

**Comment by daerduoCarey** [comment]
We refer you to the PointNet++ code repo: https://github.com/charlesq34/pointnet2. It's still new and keep updating.

**Comment by mf27** [comment]
Thank you! I forgot to check charlesq34 repos before asking :).
