### ISSUE TITLE
Data Availabilty

### ISSUE THREAD

**Issue by bradasteiner** [charlesq34/pointnet#47]
Great work! I'm excited to try this out.

I'm having an issue fetching the data, the connection has been timing out today and yesterday for
`wget https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip`

It does not seem like  https://shapenet.cs.stanford.edu/ is available from a browser either. Are there any other sources of this data? I checked out the Princeton ModelNet40 set, but the files are of type .off instead of hdf5.

**Comment by charlesq34** [comment]
The server was down for a while. It should be up now.
