### ISSUE TITLE
about training date generation pipeline

### ISSUE THREAD

**Issue by SJTUzhanglj** [charlesq34/pointnet#5]
Hello.Thanks for your excellent job. I read your code and do not find a pipeline demo on how to convert the modelnet40 files (.off file) into hdf5 files, though the functions in utils are provided. Could you please enrich your document or code with such demos. I'll be appreciated if you could reply soon.

**Comment by daerduoCarey** [comment]
Hi, thank you for your interests in our paper. Here is an example script to use save_h5 function in the utils.py code. https://gist.github.com/daerduoCarey/d91a0983140acbb8bc6455f58cbf45cb This script load all the point cloud data from ply files and store them in hdf5 file format sequentially. Hope this helps.

**Comment by SJTUzhanglj** [comment]
So the h5 files are directy converted from .ply files instead of .off files as on modelnet40, so you first convert the .off files into .ply？
  


来自 魅族 MX5

-------- 原始邮件 --------
发件人：Kaichun Mo <notifications@github.com>
时间：周一 4月17日 14:06
收件人：charlesq34/pointnet <pointnet@noreply.github.com>
抄送：SJTUzhanglj <z451155064@sjtu.edu.cn>,Author <author@noreply.github.com>
主题：Re: [charlesq34/pointnet] about training date generation pipeline (#5)

**Comment by daerduoCarey** [comment]
It's not important. You can do either way. Thank you.
