### ISSUE TITLE
model retrieval

### ISSUE THREAD

**Issue by linakrs** [charlesq34/pointnet#51]
I just want more information about model retrieval part from your article. How can I pull datas for nearest neighbor search? Do you have that part of the code?

**Comment by charlesq34** [comment]
Hi @linakrs 

I think you refer to the experiment in our appendix/supp. Basically you need to firstly train a network (for example, for classification) and then extract feature vectors (from last non-linear layer) for all training set shapes. Then during test, given a new shape, firstly extract the feature vector and then compare this vector to the pre-extracted training set vectors to find the nearest one.

Let me know if there is anything unclear :)

**Comment by charlesq34** [comment]
closing due to no continuing conversation.
