### ISSUE TITLE
Can PointNet deal with varyinig densities?

### ISSUE THREAD

**Issue by Merlin1896** [charlesq34/pointnet#53]
In my application, the measured points are not equally spaced. Some regions are empty and then there are some regions with rather high density. Is pointnet able to deal with this?
Here is an example image for which I would like to do semantic segmentation:
![image](https://user-images.githubusercontent.com/21171829/31876008-d1184082-b7d0-11e7-843c-37b53c225ceb.png)

**Comment by charlesq34** [comment]
PointNet is quite robust to sampling density according to our experiments :)

**Comment by Merlin1896** [comment]
Is it robust by design to varying densities or does the performance of the network decrease if the density is not homogeneous? Your studies in the paper seems to be done on samples, where the density of the points is rather high. In my case the interesting regions are sometimes not very dense. Do you expect problems at any stage and how could one heal this?

**Comment by charlesq34** [comment]
Hi @Merlin1896 the robustness if by design (of the max pooling layer). It's very insensitive to the density and can deal with varying density very well.

In [PointNet++](https://github.com/charlesq34/pointnet2) we need multi-scale layers for varying density cases.
