### ISSUE TITLE
Hardware used

### ISSUE THREAD

**Issue by CptDD** [charlesq34/pointnet#54]
Hello, thank you for making this software tool available. I have been testing it in the last days and I would like to ask you what hardware did you use for training, testing or more precisely what kind of GPUs? I am asking this because  on the computer that I am testing, I get numerous "Out of memory exceptions"?

Sincerely,
CptD

**Comment by charlesq34** [comment]
Hi I used GTX 1080 and Titan X for training and evaluation. How large is your GPU memory capacity? You can try to reduce batch size to fit the mini-batch in memory

**Comment by CptDD** [comment]
Thank you for the information and quick reply, I did reduce the batch size before asking and the training and evaluation went well, but I wanted to know more about the hardware it was developed and tested on. One more time thank you.
