### ISSUE TITLE
Permutation of input points

### ISSUE THREAD

**Issue by Merlin1896** [charlesq34/pointnet#55]
In your paper you mention that pointcloud was specifically build to deal with permutations of the input data. You notice that point sets in R^n have the property that they are unordered, unlike pixels in an image.
I would like to understand in more detail, how you achieve this.
From models/pointnet_cls.py I infer that you start with a transformation of the point cloud (transform network) followed by two convolution layers, further transformation of the generated features, three more convolution layers and then max-pooling plus fully connected layers for output.

Lets leave the transformation networks aside for a moment because I think they are not important for the general understanding.
So the essential part - I guess - is the combination of convolution first and then a maxpooling layer. As I understand it, the convolution is done over whole points cloud, i.e. the kernels are moved over the whole input tensor (with given stride and size of the kernels). I would now assume that the output of the convolution layers is different, when the order of the input point cloud is changed. Why and how do you guarantee that the max pooling layer accounts for that and that the output after max pooling is always the same, no matter what the order of the input points is.

I saw in your paper Theorem 1 which states that it is possible to approximate a set function f by a cont. and symmetric function g up to an error epsilon. The proof you give in the appendix is rather abstract so I would love to see how the argument works here in practice with the convolution layers.

Also: have you performed experiments where you varied the input order of the points?

EDIT: I think I can answer my own question: I went through your code and realized that ALL convolutions are done on single points, that is the convolution filters NEVER extend over more than one point. Hence, there is no direct "interaction" between the points during convolution. Only the weight sharing seems to cause the exchange of information from one point to the other. Interesting that this works!

**Comment by charlesq34** [comment]
HI @Merlin1896 
Your understanding is correct. You can check out our recent NIPS work PointNet++ (http://stanford.edu/~rqi/pointnet2/) that is a hierarchical feature learning network based on PointNet.

**Comment by WangZhouTao** [comment]
@charlesq34 Is pointnet++ also permutation of the input data?
