### ISSUE TITLE
About the outdoor scene point cloud segmentation problem

### ISSUE THREAD

**Issue by luoxiaoliaolan** [charlesq34/pointnet#57]
Hi!
   I have learned this repository for a long time, and I would like to use the pointnet to solve the problem of point cloud classification in outdoor scenes. I've got some results:
![10___10___area6____________](https://user-images.githubusercontent.com/20394855/32698984-4c8b2f36-c7e9-11e7-83b4-68280741de3a.png)
The picture above is the result of urban street point cloud segmentation and I am satisfied with this result.
So I would like to try a larger outdoor scene point cloud segmentation. I got some  outdoor scene point cloud dataset, and each of them is about 1.2G.  I manually divided them into some categories. Just like this:
![2017-11-12 20_07_18____________](https://user-images.githubusercontent.com/20394855/32698992-73dd8e30-c7e9-11e7-853a-0a7b074cb98d.png)

Follow this repo's step, I converted the classified point cloud data into .npy format, according to collect_indoor3d_data.py
![2017-11-12 20_08_28____________](https://user-images.githubusercontent.com/20394855/32699031-195ff938-c7ea-11e7-9811-42b21a09341d.png)
Than I try to converted these .npy data into hdf5 format by executing gen_indoor3d_h5.py. And the total data converted to 4.2G.(NUM_POINT=4096, H5_BATCH_SIZE=1000)
![2017-11-12 20_05_53____________](https://user-images.githubusercontent.com/20394855/32699055-7d4492ec-c7ea-11e7-8465-79e45a86a1e6.png)
I've tried to train these data, and the corresponding training file parameters are here(train.py):
![2017-11-12 20_06_40____________](https://user-images.githubusercontent.com/20394855/32699146-bcccca64-c7eb-11e7-9554-cb5078f0fcc8.png)
BUT , I always got this kind of error, and I can't go on with the training
![2017-11-12 20_05_08____________](https://user-images.githubusercontent.com/20394855/32699204-f6a91b74-c7ec-11e7-9959-f64845c83a5c.png)
![2345 20171112210729](https://user-images.githubusercontent.com/20394855/32699271-b5ab45f6-c7ed-11e7-8836-367d09908245.jpg)

 (IndexError: index 89000 is out of bounds for axis 0 with size 89000)
I've tried to tune some parameters(batch_size ,H5_BATCH_SIZE) but it didn't work.
Could you please help me to solve this problem? I am looking forward to hearing from you soon. Thank a lot!!

**Comment by michael5lin** [comment]
hi there,can you leave me(or viewer) a contact info to discuss with you?

**Comment by luoxiaoliaolan** [comment]
@michael5lin  Yes！ But I only have WeChat account , and I can't use Twitter or Facebook,  you can also contact me by email. My email is :1512773416@qq.com

**Comment by charlesq34** [comment]
I think the error is due to some bug in the data preparation code. Let me know if you find it's due to a deeper reason. I'm closing the issue for now

**Comment by luoxiaoliaolan** [comment]
@charlesq34 
I found this error is indeed due to data conversion error, and the .npy files converted without the class labels. This time I only had a small sample of ourdoor scenes, and the scene of the number of point cloud is about 30 million. And I initially fine-tuned the parameters of the training network to perform the training. But I got worse test results. Just like this:
![_20171201105608](https://user-images.githubusercontent.com/20394855/33466090-acf924c6-d686-11e7-818f-22e716b8038a.png)
It shows that pointnet may not be able to effectively handle large-scale outdoor scene point cloud data.
So I would like to try your PointNet++, but the code for this Repo does not to have been completed, and I want to know about the specific of it.

**Comment by bingo830422** [comment]
@luoxiaoliaolan 
Hello, could you share the visualizing code with me. I had trouble in result visualizing.

**Comment by bw4sz** [comment]
@luoxiaoliaolan
Do you have suggestions about choosing an appropriate number of fixed points for outdoor scenes? Did you really set it to 30 million! Did it fit into GPU? Given that each scene will always have a different number of points, how do you go about deciding on the fixed value to sample?

**Comment by luoxiaoliaolan** [comment]
@bw4sz Hi!
    The outdoor scene I used are almost 30 million points. Through experiments I have found that this repo may not be able to fully adapt to the classification of outdoor scene point clouds, and can improve the classification effect after fine-tuning some training parameters. The impact of the number of pointclouds on the classification results of outdoor scenes is still under study. I also hope you have some new ideas to discuss with me.

**Comment by bw4sz** [comment]
hi @luoxiaoliaolan !

I am working on outdoor scenes from real images, not benchmark data. Are you working on a benchmark dataset?

What i'm trying to solve this week is enforcing a fixed number of points to be fed into pointnet (or pointnet++). Correct me if i'm wrong there. What I implemented [today](https://github.com/weecology/DeepForest/blob/Lidar/DeepForest/Lidar.py) was similar to the farthest point sampling in pointnet++. First a voxelgrid is overlaid on the cloud to regularize the point cloud. See [here](http://www.open3d.org/docs/tutorial/Basic/pointcloud.html#voxel-downsampling). This enforces a general downsampling and tries to keep the overall structure. From there, I find the distance to the closest neighbor for each point. I use this vector to weight a random sampling of the array, such that points with close neighbors are less likely to be sampled. This is a computationally expensive task. If there are fewer points in a scene than the fixed number, I sample with replacement to create duplicates. I haven't read anywhere what effect this duplication has, but i've seen others do it. I might change the 'minimum distance' to 'mean distance' tomorrow, perhaps less sensitive to outliers?  All thoughts welcome.

In terms of quantitative tests, i recently read the thesis by @themmes [pdf](https://www.dropbox.com/s/flhfrmpc8135i66/thesis_themmes.pdf?dl=0) and @monocloud [pdf](https://www.dropbox.com/s/h7mkfhwqjdr1pic/MA_Foltyn.pdf?dl=0) who did a number of pointnet and similar tests of robustness

**Comment by themmes** [comment]
For my thesis I performed a similar experiment (only with PointNet, not PointNet++). I subsampled each sample to a fixed number randomly (original codebase), voxelgrid subsampling and preserving density variation and a voxelgrid subsampling with flattening density variations. With about 4k points the results of these different methods did not vary, when I lowered the number of points to 100 the voxelgrid methods significantly outperform random sampling.

Im really interested how your experiment performs on both PointNet and PointNet++. Dont you think it will have even less effect on PointNet++?

**Comment by luoxiaoliaolan** [comment]
Hi! @bw4sz 
   I browse the homepage of your team，and I feel your team’s research is awesome.  I believe that the difficulty of pointcloud semantic segmentation using deep learning lies not only in the construction of the CNN layers to extract the features of the point cloud data, but also in the processing of point cloud data. There are now some point cloud data sampling methods, but this is aim to some specific scenes, such as indoor scenes and outdoor scenes, are not the same.
The situation of point cloud data obtained by scanning trees is much more complicated because the distribution of point clouds in trees is not uniform and the processing of tree point clouds is also more difficult.
I am very interested in your ecological research and hope to learn more!!

**Comment by pournami123** [comment]
@luoxiaoliaolan  could you please share the visualization code with me. It would be of great help
