### ISSUE TITLE
Why T-net is not used in semantic segmentation model

### ISSUE THREAD

**Issue by shuluoshu** [charlesq34/pointnet#58]
Hi, @charlesq34 , thanks for your kind work, after studying your code, I found that the "model.py" under  the "sem_seg" folder does not implement the T-net part mentioned in your paper, I wonder why. 

Besides, I have another question, I notice the input data is in a form of "XYZRGBX'Y'Z' ", while the x' = x/max_room_x, y' = y/max_room_y, z'= z/max_room_z, what is the reason for the additional x'y'z' ?

Thanks a lot! 
Hope to see your kind reply!

**Comment by charlesq34** [comment]
Hi @shuluoshu 

Since for segmentation there could be more than one objects in an input point cloud sample, so it's hard for the network to find a "canonical" pose for it.

In contrast, for *single* object classification, T-net makes much more sense.

**Comment by croros** [comment]
Is there a similar reason as to why T-Net is not used in PointNet++?

**Comment by mashnoon1234** [comment]
Hi @charlesq34! 

First of all, I really appreciate the scientific contributions you have made in this domain. 

I was going through your PointNet paper and I believe you only mentioned the structures of the classification and part segmentation networks in the paper. If that is the case, do these two files ([model.py](https://github.com/charlesq34/pointnet/blob/master/sem_seg/model.py) and [pointnet_seg.py](https://github.com/charlesq34/pointnet/blob/master/models/pointnet_seg.py)) contain the basic structure for your indoor scene semantic segmentation network?

Hoping to hear from you soon!
