### ISSUE TITLE
Issue to download trial data

### ISSUE THREAD

**Issue by evagap** [charlesq34/pointnet#62]
Hello,

I tried to download the trial data (ModelNET40) and I get the following error:
--2017-12-05 16:45:27--  https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip;
Resolving shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)... 
Connecting to shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)|... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-12-05 16:45:28 ERROR 404: Not Found.

--2017-12-05 16:45:28--  http://unzip/
Resolving unzip (unzip)... failed: No such host is known. .
wget: unable to resolve host address 'unzip'
--2017-12-05 16:45:30--  http://modelnet40_ply_hdf5_2048.zip/
Resolving modelnet40_ply_hdf5_2048.zip (modelnet40_ply_hdf5_2048.zip)... failed: No such host is known. .
wget: unable to resolve host address 'modelnet40_ply_hdf5_2048.zip'
'mv' is not recognized as an internal or external command,
operable program or batch file.
'rm' is not recognized as an internal or external command,
operable program or batch file.

I have checked that I have access in the repository. 

Could you advise me on what to do?

Thank you.

**Comment by charlesq34** [comment]
It should be due to temporary shutdown of the server. Should be resolved now. Closing
