### ISSUE TITLE
About implementation and transformations

### ISSUE THREAD

**Issue by ceteke** [charlesq34/pointnet#64]
Hi,

First of all great work! But I have some questions:

1) Your implementation is using Conv2D and in the first layer it has kernel size of (1,3) so it is basically taking linear combinations of the coordinates (assume no activation here). So instead of using Conv2D using Conv1D on the points and taking the x, y, z coordinates as channels should be the same right? Is there a reasong why you prefer Conv2D?

2) I did not understand the underlying theory for using the transformation nets. I get the fact that the network should not be effected by the transformations but we are not learning transformations separately. Can you provide me a document so I can understand what is going on there?

**Comment by charlesq34** [comment]
Hi @ceteke. sorry for the delay in response.

Yes, using conv1D will have the same effect. Time wise they are also similar. Or you can even use batch mode matrix multiplication + RELU

I'll refer you to this paper for the transformation network, the philosophy behind is very similar: https://arxiv.org/abs/1506.02025

Best,
Charles
