### ISSUE TITLE
Training time for part segmentation model

### ISSUE THREAD

**Issue by Aki1987** [charlesq34/pointnet#66]
Thank you for your great work.
I did all step as you wrote.
No error here howerver the training for part segmentation model (cmd: python train.py) is taking too much time. I don't know why because My computer has 32G memory, has GPU. 
I think I did forgot anything.
Please help me!
Best,
Aki

**Comment by Aki1987** [comment]
I have one more question. In part segmentation model, I want to try convert my dataset to h5 files. 
my dataset I config with same structure with PartAnnotation of shapenet. 
Can you provide code to solve this problem.
Thank you so much.

**Comment by luoxiaoliaolan** [comment]
@Aki1987 Maybe you can use gen_indoor3d_h5.py in folder "sem_seg", and this python file can convert your dataset into h5 files.  Just try it!

**Comment by Aki1987** [comment]
Thanks @luoxiaoliaolan.

**Comment by luoxiaoliaolan** [comment]
@Aki1987  I can't understand the file structure and format in folder "PartAnnotation"  and this folder is about Part segmentation. Can you use your own point cloud data into that format??

**Comment by Aki1987** [comment]
@luoxiaoliaolan Thank you for your reply.
Data structure collects some categories. Each category has some parts. Each part has 1 point cloud file .pts . I can modify pts file if it is necessary.
I am trying gen_indoor3d_h5.py but it has some error.

**Comment by SIMONNNNNNNNNN** [comment]
@Aki1987 Could you let me know how much time you spent on classification training? I think I come across some issues, I have been running the training process for 20 hours but only finish a small part. Thank you.

**Comment by charlesq34** [comment]
Hi @SIMONNNNNNNNNN I know it has been a while.. Hope your problem has already been resolved.

Anyway, I suggest check the loss curves using TensorBoard to see if loss decreases normally for both training and testing set. The part segmentation does take a few days to train I believe.
You can also use nvidia-smi in command line to check whether you have high GPU usage -- sometimes if IO takes too much time GPU will be idle.

Hope it helps. Let me know if you have more questions.

**Comment by SIMONNNNNNNNNN** [comment]
@charlesq34 Thanks for your reply. It was because of some gpu issues, and already solved. 
PointNet is really a nice work, thank you again.
