### ISSUE TITLE
GPU to use

### ISSUE THREAD

**Issue by yoshiyama** [charlesq34/pointnet#68]
I would like to use GPU for processing faster.
Therefore I would like to know how to set GPU.
Optional arguments include GPU setting ( --gpu GPU             GPU to use [default: GPU 0]).
What does "0" in GPU 0 here mean ?
For example it does not process faster with --gpu 0 and --gpu 1, respectively.

My PC has a NVIDIA GeForde 1080.

Let me know how to use GPU.

**Comment by themmes** [comment]
If your computer/server has a (or multiple) dedicated GPU(s) these are generally numbered starting with 0. If Tensorflow is not able to find a GPU it will log this explicitly.
