### ISSUE TITLE
About the regularization term of T-Net?

### ISSUE THREAD

**Issue by kakaxi314** [charlesq34/pointnet#74]
I'm new to tensorflow, and I'm not sure if the regularization term of T-Net implemented in code?

**Comment by jbregli** [comment]
Hi,

It is implemented at: https://github.com/charlesq34/pointnet/blob/d64d2398e55b24f69e95ecb549ff7d4581ffc21e/models/pointnet_cls.py#L82

**Comment by kakaxi314** [comment]
@jbregli Thanks.
