### ISSUE TITLE
Bitwise operation on data

### ISSUE THREAD

**Issue by evagap** [charlesq34/pointnet#78]
Hello Charles,

I have a question on the "sem-segm" part of the code. Why do you use bitwise operations to find the number of points in each block?

Thank you very much for your time.

**Comment by charlesq34** [comment]
Hi @evagap , sorry for the late response, could you refer to the code line number?

**Comment by evagap** [comment]
Hello @charlesq34 , it is the "indoor3d_util" file under the ""sem_segm" part and more specifically lines 196-198. I attach them here as well:
xcond = (data[:,0]<=xbeg+block_size) & (data[:,0]>=xbeg)
       ycond = (data[:,1]<=ybeg+block_size) & (data[:,1]>=ybeg)
       cond = xcond & ycond

Thank you for your time

**Comment by charlesq34** [comment]
Hi @evagap 

`data` is a N by 6 array, so `data[:,0]` is an 1D array, thus after bitwise AND operations, `cond` is also an 1D array of True and False. Taking the sum of `cond` results in the number of points satisfying our conditions.

Hope it helps.

**Comment by evagap** [comment]
Thank you! It is helpful!
