### ISSUE TITLE
Confusion about pointcloud data generation

### ISSUE THREAD

**Issue by lszh2015** [charlesq34/pointnet#8]
Hi Charles,

Thank you for your state-of-the-art work and code. It's really a brand new method to utilize the 3D raw data. I'm interested in the 3D object classification based on ModelNet40. Here is the question.

The point number of the data is fixed to 2048 in the hdf5 file. But when I turn to ModelNet40, the vertices numbers of models are always more or less than 2048. It's easy to sample from models with vertices numbers more than 2048, but how to deal with the models with vertices less than 2048 even 1024? (for example wardrobe_000000112.off, only with 46 vertices)

I have tried to use MeshLab to mesh models and then uniformly sample 2048 points from the mesh. But when I use these data to train and test, the test accuracy is only about 86.0%, far less than about 89.1% based on the hdf5 file. Could you please share the method to generate pointcloud data?

PS: In the last paragraph of Appendix C, maybe by using Adam optimizer, momentum parameter is not needed?

I'll be appreciated if you could reply soon.

Many thanks,
Jerry Li

**Comment by charlesq34** [comment]
Hi Jerry,

We randomly sample points on mesh faces with probabilities according to face areas. You can find some code in PCL: 
https://github.com/PointCloudLibrary/pcl/blob/master/tools/mesh_sampling.cpp

We can sample whatever number of points in that way and then do a farthest point sampling to subsample them into 1024 or 2048 points. Skipping the farthest sampling is also okay and shouldn't affect results too much.

Hope it helps.
Charles

**Comment by lszh2015** [comment]
Thank you for your help. I'm trying to use PCL library. :)

**Comment by lszh2015** [comment]
Hi Charles, 

I have tried to use PCL library, but came to a failure. Actually I'm not good at C++ and I don't know how to set parameters such as leaf size to match the problem. Could you please provide the pointcloud generation code or raw pointcloud data with their label names (for example, airplane_0001.xyz, etc) to compare with data I generated. 

Thanks,
Jerry Li

**Comment by lszh2015** [comment]
Hi Charles,

When I use mesh_sampling.cpp to sample the mesh data, I find that how to select the leaf size is a question. When I use a specific value (for example, leaf_size=0.005) in batch processing, there are always some pointclouds cannot adapt the leaf size because the size of the pointclouds are too large or too small. How to deal with this problem?

I'll be appreciated if you could reply soon.

Many thanks,
Jerry Li

**Comment by charlesq34** [comment]
Hi Jerry,

You can normalize the mesh in a preprocessing step and set a very small leaf size.

Best,
Charles

**Comment by eriche2016** [comment]
Hi,@charlesq34 , can you share the code or clarify pipeline  on generating the point cloud data from .off files? much obliged if you do.

**Comment by goog** [comment]
@charlesq34 where is  farthest point sampling api
