### ISSUE TITLE
Can I increase the points' number for the training process?

### ISSUE THREAD

**Issue by Imy16** [charlesq34/pointnet#80]
Hello,

Thank you for your great work. It is very interesting.
I am wondering if it is possible to increase the points' number (>2048) in the PointNet architecture?
If yes. how ?

Thank you in advance.

**Comment by charlesq34** [comment]
Hi @Imy16 

Yes it is possible, in https://github.com/charlesq34/pointnet2 -> Download Data, we provide sampled point clouds with 10,000 points.

You will either have to re-prepare the HDF5 files according to code script similar to this one: https://github.com/charlesq34/3dmodel_feature/blob/master/io/write_hdf5.py

or you can use the data provider script in the pointnet2 repository.

Best,
Charles
