### ISSUE TITLE
T-nets

### ISSUE THREAD

**Issue by rdiazgarHP** [charlesq34/pointnet#81]
Hi,

I was just wondering. Is there any particular reason for not enforcing orthogonality to the transform_XYZ net, but to do so in the transform_feat one? It seems to me that the first T-net can roam free to transform the input cloud, and only the second T-net contributes to the loss by orthogonal enforcement. Why not enforce the first T-net too?

Regards,
Raul

**Comment by charlesq34** [comment]
Hi @rdiazgarHP 

You can also restrict the matrix to be rotations only. Currently the 3x3 matrix has a more free form such that it can also skew or scale the point clouds.
For the 64x64 transformation matrix we found a regularization of orthogonality makes optimization more controllable and leads to better performance.

Best,
Charles

**Comment by rdiazgarHP** [comment]
I see. Thanks for the clarification!

**Comment by adosar** [comment]
> Hi @rdiazgarHP
> 
> You can also restrict the matrix to be rotations only. Currently the 3x3 matrix has a more free form such that it can also skew or scale the point clouds. For the 64x64 transformation matrix we found a regularization of orthogonality makes optimization more controllable and leads to better performance.
> 
> Best, Charles

Hello @charlesq34! How can the rotation matrix be forced to represent only rotations? Moreover, would be a good idea to substitute T-Net with data augmentation (e.g. every kind of rotation)?
