### ISSUE TITLE
Question about symmetric function max pooling

### ISSUE THREAD

**Issue by godspeed1989** [charlesq34/pointnet#86]
Hi,
i notice the symmetric function `max pooling`:
```
    net = tf_util.max_pool2d(net, [num_point,1],
                `padding='VALID',` scope='maxpool')
```
the pooling function use the default `stride` value `[2, 2]`
```
def max_pool2d(inputs,
               kernel_size,
               scope,
               stride=[2, 2],
               padding='VALID'):
```
may be it shoud be `[1,1]`?

**Comment by huipengly** [comment]
I have the same question. Could you explain it to   @godspeed1989 

我也有这个疑问，能不能解释下你为啥关了这个issue？

**Comment by godspeed1989** [comment]
Because the input to this layer is [B, num_point, 1, C] and kernel size here is  [num_point,1], which means the [2,2] stride here wouldn't has any effect.

**Comment by huipengly** [comment]
Many thanks.
