### ISSUE TITLE
Which hardware specs should be enough to train pointNet?

### ISSUE THREAD

**Issue by FilipaRamos** [charlesq34/pointnet#88]
Hi! 
Thanks for your great work, I find PointNet imensely interesting.

I am wondering specially about the GPU and how much dedicated memory I should have in order to train pointnet on a custom dataset efficiently.

Thanks!

**Comment by charlesq34** [comment]
HI @FilipaRamos 

PointNet does not require very large memory for training, with batch size 32, `pointnet_cls` requires around 2.4G, `pointnet_cls_basic` requires around 1.3G. The segmentation models would require more memory though, but you can set smaller batch size to make it fit.

specifically we are using GTX 1080 and Titan Xp for our training.

**Comment by FilipaRamos** [comment]
Thanks @charlesq34 !
