### ISSUE TITLE
How to use my own data for part segmentation?

### ISSUE THREAD

**Issue by IsaacGuan** [charlesq34/pointnet#94]
Thank you so much for sharing the code!
In a previous issue [How to prepare my own data set for the segmentation training?](https://github.com/charlesq34/pointnet/issues/75) you mentioned that we can reference the script here: https://github.com/charlesq34/3dmodel_feature/blob/master/io/write_hdf5.py to generate the HDF5 files. I looked into that code, it only takes two types of information to the HDF5 file, which are `h5_batch_data` and `h5_batch_label`. However, for part segmentation we should also introduce an additional dimension which includes the part information. And actually the structure of HDF5 file for part segmentation looks like this:
![screenshot from 2018-03-28 22-07-01](https://user-images.githubusercontent.com/20313286/38066080-6d3a187c-32d4-11e8-9c7c-ea3570972e06.png)
The view of "pid" contains the part information for each point cloud. But the problem is how can this be written to HDF5 files?
As I have some ready made segmented point clouds with extra channel representing the parts in the structure of (X, Y, Z, Pid), I really want to use your implementation to explore further on my own dataset. The "write_hdf5.py" has very few comments in it, so I would be really appreciated if you could give me some hints on this issue!

**Comment by IsaacGuan** [comment]
I think I have found one possible approach. With a simple tool called [plyfile](https://github.com/dranjan/python-plyfile), we can read the points from .ply file as a numpy array. Then we simply write these arrays into HDF5 files using [h5py](https://www.h5py.org/) library.
This is how I did: https://github.com/IsaacGuan/PointNet-Plane-Detection/blob/master/data/write_hdf5.py

**Comment by sivaprasadraju** [comment]
Hello All,
I wanted to train PointNet for classification only. I have pointcloud data(x, y, z, i) in .bin format and corresponding labels in .txt format.

Can anyone please help me how to train PointNet with this data?

**Comment by cystal-lili** [comment]
Have you solved your question? If you like, can I ask you questions
My qq1922797937
thank you very much
